// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: browserd.proto

package browserdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClipboardMode int32

const (
	ClipboardMode_CLIPBOARD_MODE_UNSPECIFIED ClipboardMode = 0
	ClipboardMode_CLIPBOARD_MODE_VIRTUAL     ClipboardMode = 1
	ClipboardMode_CLIPBOARD_MODE_HOST        ClipboardMode = 2
)

// Enum value maps for ClipboardMode.
var (
	ClipboardMode_name = map[int32]string{
		0: "CLIPBOARD_MODE_UNSPECIFIED",
		1: "CLIPBOARD_MODE_VIRTUAL",
		2: "CLIPBOARD_MODE_HOST",
	}
	ClipboardMode_value = map[string]int32{
		"CLIPBOARD_MODE_UNSPECIFIED": 0,
		"CLIPBOARD_MODE_VIRTUAL":     1,
		"CLIPBOARD_MODE_HOST":        2,
	}
)

func (x ClipboardMode) Enum() *ClipboardMode {
	p := new(ClipboardMode)
	*p = x
	return p
}

func (x ClipboardMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClipboardMode) Descriptor() protoreflect.EnumDescriptor {
	return file_browserd_proto_enumTypes[0].Descriptor()
}

func (ClipboardMode) Type() protoreflect.EnumType {
	return &file_browserd_proto_enumTypes[0]
}

func (x ClipboardMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClipboardMode.Descriptor instead.
func (ClipboardMode) EnumDescriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{0}
}

type FrameFormat int32

const (
	FrameFormat_FRAME_FORMAT_UNSPECIFIED FrameFormat = 0
	FrameFormat_FRAME_FORMAT_PNG         FrameFormat = 1
	FrameFormat_FRAME_FORMAT_JPEG        FrameFormat = 2
	FrameFormat_FRAME_FORMAT_WEBP        FrameFormat = 3
)

// Enum value maps for FrameFormat.
var (
	FrameFormat_name = map[int32]string{
		0: "FRAME_FORMAT_UNSPECIFIED",
		1: "FRAME_FORMAT_PNG",
		2: "FRAME_FORMAT_JPEG",
		3: "FRAME_FORMAT_WEBP",
	}
	FrameFormat_value = map[string]int32{
		"FRAME_FORMAT_UNSPECIFIED": 0,
		"FRAME_FORMAT_PNG":         1,
		"FRAME_FORMAT_JPEG":        2,
		"FRAME_FORMAT_WEBP":        3,
	}
)

func (x FrameFormat) Enum() *FrameFormat {
	p := new(FrameFormat)
	*p = x
	return p
}

func (x FrameFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_browserd_proto_enumTypes[1].Descriptor()
}

func (FrameFormat) Type() protoreflect.EnumType {
	return &file_browserd_proto_enumTypes[1]
}

func (x FrameFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameFormat.Descriptor instead.
func (FrameFormat) EnumDescriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{1}
}

type ScrollUnit int32

const (
	ScrollUnit_SCROLL_UNIT_UNSPECIFIED ScrollUnit = 0
	ScrollUnit_SCROLL_UNIT_PIXELS      ScrollUnit = 1
	ScrollUnit_SCROLL_UNIT_LINES       ScrollUnit = 2
)

// Enum value maps for ScrollUnit.
var (
	ScrollUnit_name = map[int32]string{
		0: "SCROLL_UNIT_UNSPECIFIED",
		1: "SCROLL_UNIT_PIXELS",
		2: "SCROLL_UNIT_LINES",
	}
	ScrollUnit_value = map[string]int32{
		"SCROLL_UNIT_UNSPECIFIED": 0,
		"SCROLL_UNIT_PIXELS":      1,
		"SCROLL_UNIT_LINES":       2,
	}
)

func (x ScrollUnit) Enum() *ScrollUnit {
	p := new(ScrollUnit)
	*p = x
	return p
}

func (x ScrollUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrollUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_browserd_proto_enumTypes[2].Descriptor()
}

func (ScrollUnit) Type() protoreflect.EnumType {
	return &file_browserd_proto_enumTypes[2]
}

func (x ScrollUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrollUnit.Descriptor instead.
func (ScrollUnit) EnumDescriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{2}
}

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED     ActionType = 0
	ActionType_ACTION_TYPE_CLICK           ActionType = 1
	ActionType_ACTION_TYPE_TYPE            ActionType = 2
	ActionType_ACTION_TYPE_SCROLL          ActionType = 3
	ActionType_ACTION_TYPE_HOVER           ActionType = 4
	ActionType_ACTION_TYPE_KEY             ActionType = 5
	ActionType_ACTION_TYPE_FOCUS           ActionType = 6
	ActionType_ACTION_TYPE_CLIPBOARD_READ  ActionType = 7
	ActionType_ACTION_TYPE_CLIPBOARD_WRITE ActionType = 8
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_CLICK",
		2: "ACTION_TYPE_TYPE",
		3: "ACTION_TYPE_SCROLL",
		4: "ACTION_TYPE_HOVER",
		5: "ACTION_TYPE_KEY",
		6: "ACTION_TYPE_FOCUS",
		7: "ACTION_TYPE_CLIPBOARD_READ",
		8: "ACTION_TYPE_CLIPBOARD_WRITE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED":     0,
		"ACTION_TYPE_CLICK":           1,
		"ACTION_TYPE_TYPE":            2,
		"ACTION_TYPE_SCROLL":          3,
		"ACTION_TYPE_HOVER":           4,
		"ACTION_TYPE_KEY":             5,
		"ACTION_TYPE_FOCUS":           6,
		"ACTION_TYPE_CLIPBOARD_READ":  7,
		"ACTION_TYPE_CLIPBOARD_WRITE": 8,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_browserd_proto_enumTypes[3].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_browserd_proto_enumTypes[3]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{3}
}

type KeyModifier int32

const (
	KeyModifier_KEY_MODIFIER_UNSPECIFIED KeyModifier = 0
	KeyModifier_KEY_MODIFIER_SHIFT       KeyModifier = 1
	KeyModifier_KEY_MODIFIER_ALT         KeyModifier = 2
	KeyModifier_KEY_MODIFIER_CTRL        KeyModifier = 3
	KeyModifier_KEY_MODIFIER_META        KeyModifier = 4
)

// Enum value maps for KeyModifier.
var (
	KeyModifier_name = map[int32]string{
		0: "KEY_MODIFIER_UNSPECIFIED",
		1: "KEY_MODIFIER_SHIFT",
		2: "KEY_MODIFIER_ALT",
		3: "KEY_MODIFIER_CTRL",
		4: "KEY_MODIFIER_META",
	}
	KeyModifier_value = map[string]int32{
		"KEY_MODIFIER_UNSPECIFIED": 0,
		"KEY_MODIFIER_SHIFT":       1,
		"KEY_MODIFIER_ALT":         2,
		"KEY_MODIFIER_CTRL":        3,
		"KEY_MODIFIER_META":        4,
	}
)

func (x KeyModifier) Enum() *KeyModifier {
	p := new(KeyModifier)
	*p = x
	return p
}

func (x KeyModifier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyModifier) Descriptor() protoreflect.EnumDescriptor {
	return file_browserd_proto_enumTypes[4].Descriptor()
}

func (KeyModifier) Type() protoreflect.EnumType {
	return &file_browserd_proto_enumTypes[4]
}

func (x KeyModifier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyModifier.Descriptor instead.
func (KeyModifier) EnumDescriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{4}
}

type StreamEventType int32

const (
	StreamEventType_STREAM_EVENT_TYPE_UNSPECIFIED        StreamEventType = 0
	StreamEventType_STREAM_EVENT_TYPE_FRAME              StreamEventType = 1
	StreamEventType_STREAM_EVENT_TYPE_DOM_DIFF           StreamEventType = 2
	StreamEventType_STREAM_EVENT_TYPE_ACCESSIBILITY_DIFF StreamEventType = 3
	StreamEventType_STREAM_EVENT_TYPE_HIT_TEST           StreamEventType = 4
)

// Enum value maps for StreamEventType.
var (
	StreamEventType_name = map[int32]string{
		0: "STREAM_EVENT_TYPE_UNSPECIFIED",
		1: "STREAM_EVENT_TYPE_FRAME",
		2: "STREAM_EVENT_TYPE_DOM_DIFF",
		3: "STREAM_EVENT_TYPE_ACCESSIBILITY_DIFF",
		4: "STREAM_EVENT_TYPE_HIT_TEST",
	}
	StreamEventType_value = map[string]int32{
		"STREAM_EVENT_TYPE_UNSPECIFIED":        0,
		"STREAM_EVENT_TYPE_FRAME":              1,
		"STREAM_EVENT_TYPE_DOM_DIFF":           2,
		"STREAM_EVENT_TYPE_ACCESSIBILITY_DIFF": 3,
		"STREAM_EVENT_TYPE_HIT_TEST":           4,
	}
)

func (x StreamEventType) Enum() *StreamEventType {
	p := new(StreamEventType)
	*p = x
	return p
}

func (x StreamEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_browserd_proto_enumTypes[5].Descriptor()
}

func (StreamEventType) Type() protoreflect.EnumType {
	return &file_browserd_proto_enumTypes[5]
}

func (x StreamEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamEventType.Descriptor instead.
func (StreamEventType) EnumDescriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{5}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Request
	//	*Envelope_Response
	//	*Envelope_Event
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_browserd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Envelope) GetEvent() *StreamEvent {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Envelope_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type Envelope_Event struct {
	Event *StreamEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*Envelope_Request) isEnvelope_Message() {}

func (*Envelope_Response) isEnvelope_Message() {}

func (*Envelope_Event) isEnvelope_Message() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_browserd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Request struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_CreateSession
	//	*Request_Navigate
	//	*Request_Observe
	//	*Request_Act
	//	*Request_CloseSession
	//	*Request_StreamSubscribe
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_browserd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Request) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetCreateSession() *CreateSessionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_CreateSession); ok {
			return x.CreateSession
		}
	}
	return nil
}

func (x *Request) GetNavigate() *NavigateRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Navigate); ok {
			return x.Navigate
		}
	}
	return nil
}

func (x *Request) GetObserve() *ObserveRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Observe); ok {
			return x.Observe
		}
	}
	return nil
}

func (x *Request) GetAct() *ActRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Act); ok {
			return x.Act
		}
	}
	return nil
}

func (x *Request) GetCloseSession() *CloseSessionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_CloseSession); ok {
			return x.CloseSession
		}
	}
	return nil
}

func (x *Request) GetStreamSubscribe() *StreamSubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_StreamSubscribe); ok {
			return x.StreamSubscribe
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_CreateSession struct {
	CreateSession *CreateSessionRequest `protobuf:"bytes,3,opt,name=create_session,json=createSession,proto3,oneof"`
}

type Request_Navigate struct {
	Navigate *NavigateRequest `protobuf:"bytes,4,opt,name=navigate,proto3,oneof"`
}

type Request_Observe struct {
	Observe *ObserveRequest `protobuf:"bytes,5,opt,name=observe,proto3,oneof"`
}

type Request_Act struct {
	Act *ActRequest `protobuf:"bytes,6,opt,name=act,proto3,oneof"`
}

type Request_CloseSession struct {
	CloseSession *CloseSessionRequest `protobuf:"bytes,7,opt,name=close_session,json=closeSession,proto3,oneof"`
}

type Request_StreamSubscribe struct {
	StreamSubscribe *StreamSubscribeRequest `protobuf:"bytes,8,opt,name=stream_subscribe,json=streamSubscribe,proto3,oneof"`
}

func (*Request_CreateSession) isRequest_Payload() {}

func (*Request_Navigate) isRequest_Payload() {}

func (*Request_Observe) isRequest_Payload() {}

func (*Request_Act) isRequest_Payload() {}

func (*Request_CloseSession) isRequest_Payload() {}

func (*Request_StreamSubscribe) isRequest_Payload() {}

type Response struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error     *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_CreateSession
	//	*Response_Navigate
	//	*Response_Observe
	//	*Response_Act
	//	*Response_CloseSession
	//	*Response_StreamSubscribe
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_browserd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetCreateSession() *CreateSessionResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_CreateSession); ok {
			return x.CreateSession
		}
	}
	return nil
}

func (x *Response) GetNavigate() *NavigateResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Navigate); ok {
			return x.Navigate
		}
	}
	return nil
}

func (x *Response) GetObserve() *ObserveResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Observe); ok {
			return x.Observe
		}
	}
	return nil
}

func (x *Response) GetAct() *ActResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_Act); ok {
			return x.Act
		}
	}
	return nil
}

func (x *Response) GetCloseSession() *CloseSessionResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_CloseSession); ok {
			return x.CloseSession
		}
	}
	return nil
}

func (x *Response) GetStreamSubscribe() *StreamSubscribeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_StreamSubscribe); ok {
			return x.StreamSubscribe
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_CreateSession struct {
	CreateSession *CreateSessionResponse `protobuf:"bytes,4,opt,name=create_session,json=createSession,proto3,oneof"`
}

type Response_Navigate struct {
	Navigate *NavigateResponse `protobuf:"bytes,5,opt,name=navigate,proto3,oneof"`
}

type Response_Observe struct {
	Observe *ObserveResponse `protobuf:"bytes,6,opt,name=observe,proto3,oneof"`
}

type Response_Act struct {
	Act *ActResponse `protobuf:"bytes,7,opt,name=act,proto3,oneof"`
}

type Response_CloseSession struct {
	CloseSession *CloseSessionResponse `protobuf:"bytes,8,opt,name=close_session,json=closeSession,proto3,oneof"`
}

type Response_StreamSubscribe struct {
	StreamSubscribe *StreamSubscribeResponse `protobuf:"bytes,9,opt,name=stream_subscribe,json=streamSubscribe,proto3,oneof"`
}

func (*Response_CreateSession) isResponse_Payload() {}

func (*Response_Navigate) isResponse_Payload() {}

func (*Response_Observe) isResponse_Payload() {}

func (*Response_Act) isResponse_Payload() {}

func (*Response_CloseSession) isResponse_Payload() {}

func (*Response_StreamSubscribe) isResponse_Payload() {}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SessionConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_browserd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetConfig() *SessionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionInfo           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Observation   *Observation           `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_browserd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateSessionResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type NavigateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_browserd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{6}
}

func (x *NavigateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type NavigateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateResponse) Reset() {
	*x = NavigateResponse{}
	mi := &file_browserd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateResponse) ProtoMessage() {}

func (x *NavigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateResponse.ProtoReflect.Descriptor instead.
func (*NavigateResponse) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{7}
}

func (x *NavigateResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *ObserveOptions        `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_browserd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{8}
}

func (x *ObserveRequest) GetOptions() *ObserveOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ObserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_browserd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{9}
}

func (x *ObserveResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type ActRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRequest) Reset() {
	*x = ActRequest{}
	mi := &file_browserd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRequest) ProtoMessage() {}

func (x *ActRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRequest.ProtoReflect.Descriptor instead.
func (*ActRequest) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{10}
}

func (x *ActRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type ActResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ActionResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActResponse) Reset() {
	*x = ActResponse{}
	mi := &file_browserd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActResponse) ProtoMessage() {}

func (x *ActResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActResponse.ProtoReflect.Descriptor instead.
func (*ActResponse) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{11}
}

func (x *ActResponse) GetResult() *ActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_browserd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{12}
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_browserd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{13}
}

func (x *CloseSessionResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type StreamSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *StreamOptions         `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSubscribeRequest) Reset() {
	*x = StreamSubscribeRequest{}
	mi := &file_browserd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSubscribeRequest) ProtoMessage() {}

func (x *StreamSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSubscribeRequest.ProtoReflect.Descriptor instead.
func (*StreamSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{14}
}

func (x *StreamSubscribeRequest) GetOptions() *StreamOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type StreamSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribed    bool                   `protobuf:"varint,1,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSubscribeResponse) Reset() {
	*x = StreamSubscribeResponse{}
	mi := &file_browserd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSubscribeResponse) ProtoMessage() {}

func (x *StreamSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSubscribeResponse.ProtoReflect.Descriptor instead.
func (*StreamSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{15}
}

func (x *StreamSubscribeResponse) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StateVersion  uint64                 `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_browserd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{16}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *SessionInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SessionConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InitialUrl       string                 `protobuf:"bytes,2,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
	Viewport         *Viewport              `protobuf:"bytes,3,opt,name=viewport,proto3" json:"viewport,omitempty"`
	UserAgent        string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Locale           string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	Timezone         string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	FrameRate        uint32                 `protobuf:"varint,7,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	NetworkAllowlist []string               `protobuf:"bytes,8,rep,name=network_allowlist,json=networkAllowlist,proto3" json:"network_allowlist,omitempty"`
	Clipboard        *ClipboardPolicy       `protobuf:"bytes,9,opt,name=clipboard,proto3" json:"clipboard,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_browserd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{17}
}

func (x *SessionConfig) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionConfig) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

func (x *SessionConfig) GetViewport() *Viewport {
	if x != nil {
		return x.Viewport
	}
	return nil
}

func (x *SessionConfig) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionConfig) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SessionConfig) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SessionConfig) GetFrameRate() uint32 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *SessionConfig) GetNetworkAllowlist() []string {
	if x != nil {
		return x.NetworkAllowlist
	}
	return nil
}

func (x *SessionConfig) GetClipboard() *ClipboardPolicy {
	if x != nil {
		return x.Clipboard
	}
	return nil
}

type Viewport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Width             uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height            uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	DeviceScaleFactor float64                `protobuf:"fixed64,3,opt,name=device_scale_factor,json=deviceScaleFactor,proto3" json:"device_scale_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Viewport) Reset() {
	*x = Viewport{}
	mi := &file_browserd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewport) ProtoMessage() {}

func (x *Viewport) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewport.ProtoReflect.Descriptor instead.
func (*Viewport) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{18}
}

func (x *Viewport) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Viewport) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Viewport) GetDeviceScaleFactor() float64 {
	if x != nil {
		return x.DeviceScaleFactor
	}
	return 0
}

type ClipboardPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          ClipboardMode          `protobuf:"varint,1,opt,name=mode,proto3,enum=buckley.browserd.v1.ClipboardMode" json:"mode,omitempty"`
	AllowRead     bool                   `protobuf:"varint,2,opt,name=allow_read,json=allowRead,proto3" json:"allow_read,omitempty"`
	AllowWrite    bool                   `protobuf:"varint,3,opt,name=allow_write,json=allowWrite,proto3" json:"allow_write,omitempty"`
	MaxBytes      uint32                 `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	ReadAllowlist []string               `protobuf:"bytes,5,rep,name=read_allowlist,json=readAllowlist,proto3" json:"read_allowlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardPolicy) Reset() {
	*x = ClipboardPolicy{}
	mi := &file_browserd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPolicy) ProtoMessage() {}

func (x *ClipboardPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPolicy.ProtoReflect.Descriptor instead.
func (*ClipboardPolicy) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{19}
}

func (x *ClipboardPolicy) GetMode() ClipboardMode {
	if x != nil {
		return x.Mode
	}
	return ClipboardMode_CLIPBOARD_MODE_UNSPECIFIED
}

func (x *ClipboardPolicy) GetAllowRead() bool {
	if x != nil {
		return x.AllowRead
	}
	return false
}

func (x *ClipboardPolicy) GetAllowWrite() bool {
	if x != nil {
		return x.AllowWrite
	}
	return false
}

func (x *ClipboardPolicy) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *ClipboardPolicy) GetReadAllowlist() []string {
	if x != nil {
		return x.ReadAllowlist
	}
	return nil
}

type ObserveOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IncludeFrame         bool                   `protobuf:"varint,1,opt,name=include_frame,json=includeFrame,proto3" json:"include_frame,omitempty"`
	IncludeDomSnapshot   bool                   `protobuf:"varint,2,opt,name=include_dom_snapshot,json=includeDomSnapshot,proto3" json:"include_dom_snapshot,omitempty"`
	IncludeAccessibility bool                   `protobuf:"varint,3,opt,name=include_accessibility,json=includeAccessibility,proto3" json:"include_accessibility,omitempty"`
	IncludeHitTest       bool                   `protobuf:"varint,4,opt,name=include_hit_test,json=includeHitTest,proto3" json:"include_hit_test,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ObserveOptions) Reset() {
	*x = ObserveOptions{}
	mi := &file_browserd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveOptions) ProtoMessage() {}

func (x *ObserveOptions) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveOptions.ProtoReflect.Descriptor instead.
func (*ObserveOptions) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{20}
}

func (x *ObserveOptions) GetIncludeFrame() bool {
	if x != nil {
		return x.IncludeFrame
	}
	return false
}

func (x *ObserveOptions) GetIncludeDomSnapshot() bool {
	if x != nil {
		return x.IncludeDomSnapshot
	}
	return false
}

func (x *ObserveOptions) GetIncludeAccessibility() bool {
	if x != nil {
		return x.IncludeAccessibility
	}
	return false
}

func (x *ObserveOptions) GetIncludeHitTest() bool {
	if x != nil {
		return x.IncludeHitTest
	}
	return false
}

type StreamOptions struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	IncludeFrames             bool                   `protobuf:"varint,1,opt,name=include_frames,json=includeFrames,proto3" json:"include_frames,omitempty"`
	IncludeDomDiffs           bool                   `protobuf:"varint,2,opt,name=include_dom_diffs,json=includeDomDiffs,proto3" json:"include_dom_diffs,omitempty"`
	IncludeAccessibilityDiffs bool                   `protobuf:"varint,3,opt,name=include_accessibility_diffs,json=includeAccessibilityDiffs,proto3" json:"include_accessibility_diffs,omitempty"`
	IncludeHitTest            bool                   `protobuf:"varint,4,opt,name=include_hit_test,json=includeHitTest,proto3" json:"include_hit_test,omitempty"`
	TargetFps                 uint32                 `protobuf:"varint,5,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StreamOptions) Reset() {
	*x = StreamOptions{}
	mi := &file_browserd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOptions) ProtoMessage() {}

func (x *StreamOptions) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOptions.ProtoReflect.Descriptor instead.
func (*StreamOptions) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{21}
}

func (x *StreamOptions) GetIncludeFrames() bool {
	if x != nil {
		return x.IncludeFrames
	}
	return false
}

func (x *StreamOptions) GetIncludeDomDiffs() bool {
	if x != nil {
		return x.IncludeDomDiffs
	}
	return false
}

func (x *StreamOptions) GetIncludeAccessibilityDiffs() bool {
	if x != nil {
		return x.IncludeAccessibilityDiffs
	}
	return false
}

func (x *StreamOptions) GetIncludeHitTest() bool {
	if x != nil {
		return x.IncludeHitTest
	}
	return false
}

func (x *StreamOptions) GetTargetFps() uint32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

type Observation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StateVersion      uint64                 `protobuf:"varint,1,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Url               string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Frame             *Frame                 `protobuf:"bytes,4,opt,name=frame,proto3" json:"frame,omitempty"`
	DomSnapshot       []byte                 `protobuf:"bytes,5,opt,name=dom_snapshot,json=domSnapshot,proto3" json:"dom_snapshot,omitempty"`
	AccessibilityTree []byte                 `protobuf:"bytes,6,opt,name=accessibility_tree,json=accessibilityTree,proto3" json:"accessibility_tree,omitempty"`
	HitTest           *HitTestMap            `protobuf:"bytes,7,opt,name=hit_test,json=hitTest,proto3" json:"hit_test,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_browserd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{22}
}

func (x *Observation) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *Observation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Observation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Observation) GetFrame() *Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Observation) GetDomSnapshot() []byte {
	if x != nil {
		return x.DomSnapshot
	}
	return nil
}

func (x *Observation) GetAccessibilityTree() []byte {
	if x != nil {
		return x.AccessibilityTree
	}
	return nil
}

func (x *Observation) GetHitTest() *HitTestMap {
	if x != nil {
		return x.HitTest
	}
	return nil
}

func (x *Observation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateVersion  uint64                 `protobuf:"varint,1,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Format        FrameFormat            `protobuf:"varint,4,opt,name=format,proto3,enum=buckley.browserd.v1.FrameFormat" json:"format,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_browserd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{23}
}

func (x *Frame) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *Frame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Frame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Frame) GetFormat() FrameFormat {
	if x != nil {
		return x.Format
	}
	return FrameFormat_FRAME_FORMAT_UNSPECIFIED
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HitTestMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Regions       []*HitRegion           `protobuf:"bytes,3,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitTestMap) Reset() {
	*x = HitTestMap{}
	mi := &file_browserd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitTestMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitTestMap) ProtoMessage() {}

func (x *HitTestMap) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitTestMap.ProtoReflect.Descriptor instead.
func (*HitTestMap) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{24}
}

func (x *HitTestMap) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *HitTestMap) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HitTestMap) GetRegions() []*HitRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

type HitRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Bounds        *Rect                  `protobuf:"bytes,2,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitRegion) Reset() {
	*x = HitRegion{}
	mi := &file_browserd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitRegion) ProtoMessage() {}

func (x *HitRegion) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitRegion.ProtoReflect.Descriptor instead.
func (*HitRegion) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{25}
}

func (x *HitRegion) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HitRegion) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_browserd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{26}
}

func (x *Rect) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_browserd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{27}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Action struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 ActionType             `protobuf:"varint,1,opt,name=type,proto3,enum=buckley.browserd.v1.ActionType" json:"type,omitempty"`
	ExpectedStateVersion uint64                 `protobuf:"varint,2,opt,name=expected_state_version,json=expectedStateVersion,proto3" json:"expected_state_version,omitempty"`
	Target               *ActionTarget          `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Text                 string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Key                  string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Scroll               *ScrollDelta           `protobuf:"bytes,6,opt,name=scroll,proto3" json:"scroll,omitempty"`
	Modifiers            []KeyModifier          `protobuf:"varint,7,rep,packed,name=modifiers,proto3,enum=buckley.browserd.v1.KeyModifier" json:"modifiers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_browserd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{28}
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *Action) GetExpectedStateVersion() uint64 {
	if x != nil {
		return x.ExpectedStateVersion
	}
	return 0
}

func (x *Action) GetTarget() *ActionTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Action) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Action) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Action) GetScroll() *ScrollDelta {
	if x != nil {
		return x.Scroll
	}
	return nil
}

func (x *Action) GetModifiers() []KeyModifier {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type ActionTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Point         *Point                 `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionTarget) Reset() {
	*x = ActionTarget{}
	mi := &file_browserd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionTarget) ProtoMessage() {}

func (x *ActionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionTarget.ProtoReflect.Descriptor instead.
func (*ActionTarget) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{29}
}

func (x *ActionTarget) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ActionTarget) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

type ScrollDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Unit          ScrollUnit             `protobuf:"varint,3,opt,name=unit,proto3,enum=buckley.browserd.v1.ScrollUnit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollDelta) Reset() {
	*x = ScrollDelta{}
	mi := &file_browserd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollDelta) ProtoMessage() {}

func (x *ScrollDelta) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollDelta.ProtoReflect.Descriptor instead.
func (*ScrollDelta) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{30}
}

func (x *ScrollDelta) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollDelta) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ScrollDelta) GetUnit() ScrollUnit {
	if x != nil {
		return x.Unit
	}
	return ScrollUnit_SCROLL_UNIT_UNSPECIFIED
}

type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateVersion  uint64                 `protobuf:"varint,1,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Observation   *Observation           `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	Effects       []*Effect              `protobuf:"bytes,3,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_browserd_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{31}
}

func (x *ActionResult) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *ActionResult) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *ActionResult) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type Effect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_browserd_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{32}
}

func (x *Effect) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Effect) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Effect) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StreamEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              StreamEventType        `protobuf:"varint,1,opt,name=type,proto3,enum=buckley.browserd.v1.StreamEventType" json:"type,omitempty"`
	StateVersion      uint64                 `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Frame             *Frame                 `protobuf:"bytes,3,opt,name=frame,proto3" json:"frame,omitempty"`
	DomDiff           []byte                 `protobuf:"bytes,4,opt,name=dom_diff,json=domDiff,proto3" json:"dom_diff,omitempty"`
	AccessibilityDiff []byte                 `protobuf:"bytes,5,opt,name=accessibility_diff,json=accessibilityDiff,proto3" json:"accessibility_diff,omitempty"`
	HitTest           *HitTestMap            `protobuf:"bytes,6,opt,name=hit_test,json=hitTest,proto3" json:"hit_test,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_browserd_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_browserd_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_browserd_proto_rawDescGZIP(), []int{33}
}

func (x *StreamEvent) GetType() StreamEventType {
	if x != nil {
		return x.Type
	}
	return StreamEventType_STREAM_EVENT_TYPE_UNSPECIFIED
}

func (x *StreamEvent) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *StreamEvent) GetFrame() *Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *StreamEvent) GetDomDiff() []byte {
	if x != nil {
		return x.DomDiff
	}
	return nil
}

func (x *StreamEvent) GetAccessibilityDiff() []byte {
	if x != nil {
		return x.AccessibilityDiff
	}
	return nil
}

func (x *StreamEvent) GetHitTest() *HitTestMap {
	if x != nil {
		return x.HitTest
	}
	return nil
}

func (x *StreamEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_browserd_proto protoreflect.FileDescriptor

const file_browserd_proto_rawDesc = "" +
	"\n" +
	"\x0ebrowserd.proto\x12\x13buckley.browserd.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc6\x01\n" +
	"\bEnvelope\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1c.buckley.browserd.v1.RequestH\x00R\arequest\x12;\n" +
	"\bresponse\x18\x02 \x01(\v2\x1d.buckley.browserd.v1.ResponseH\x00R\bresponse\x128\n" +
	"\x05event\x18\x03 \x01(\v2 .buckley.browserd.v1.StreamEventH\x00R\x05eventB\t\n" +
	"\amessage\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x04\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12R\n" +
	"\x0ecreate_session\x18\x03 \x01(\v2).buckley.browserd.v1.CreateSessionRequestH\x00R\rcreateSession\x12B\n" +
	"\bnavigate\x18\x04 \x01(\v2$.buckley.browserd.v1.NavigateRequestH\x00R\bnavigate\x12?\n" +
	"\aobserve\x18\x05 \x01(\v2#.buckley.browserd.v1.ObserveRequestH\x00R\aobserve\x123\n" +
	"\x03act\x18\x06 \x01(\v2\x1f.buckley.browserd.v1.ActRequestH\x00R\x03act\x12O\n" +
	"\rclose_session\x18\a \x01(\v2(.buckley.browserd.v1.CloseSessionRequestH\x00R\fcloseSession\x12X\n" +
	"\x10stream_subscribe\x18\b \x01(\v2+.buckley.browserd.v1.StreamSubscribeRequestH\x00R\x0fstreamSubscribeB\t\n" +
	"\apayload\"\xc4\x04\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x120\n" +
	"\x05error\x18\x03 \x01(\v2\x1a.buckley.browserd.v1.ErrorR\x05error\x12S\n" +
	"\x0ecreate_session\x18\x04 \x01(\v2*.buckley.browserd.v1.CreateSessionResponseH\x00R\rcreateSession\x12C\n" +
	"\bnavigate\x18\x05 \x01(\v2%.buckley.browserd.v1.NavigateResponseH\x00R\bnavigate\x12@\n" +
	"\aobserve\x18\x06 \x01(\v2$.buckley.browserd.v1.ObserveResponseH\x00R\aobserve\x124\n" +
	"\x03act\x18\a \x01(\v2 .buckley.browserd.v1.ActResponseH\x00R\x03act\x12P\n" +
	"\rclose_session\x18\b \x01(\v2).buckley.browserd.v1.CloseSessionResponseH\x00R\fcloseSession\x12Y\n" +
	"\x10stream_subscribe\x18\t \x01(\v2,.buckley.browserd.v1.StreamSubscribeResponseH\x00R\x0fstreamSubscribeB\t\n" +
	"\apayload\"R\n" +
	"\x14CreateSessionRequest\x12:\n" +
	"\x06config\x18\x01 \x01(\v2\".buckley.browserd.v1.SessionConfigR\x06config\"\x97\x01\n" +
	"\x15CreateSessionResponse\x12:\n" +
	"\asession\x18\x01 \x01(\v2 .buckley.browserd.v1.SessionInfoR\asession\x12B\n" +
	"\vobservation\x18\x02 \x01(\v2 .buckley.browserd.v1.ObservationR\vobservation\"#\n" +
	"\x0fNavigateRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"V\n" +
	"\x10NavigateResponse\x12B\n" +
	"\vobservation\x18\x01 \x01(\v2 .buckley.browserd.v1.ObservationR\vobservation\"O\n" +
	"\x0eObserveRequest\x12=\n" +
	"\aoptions\x18\x01 \x01(\v2#.buckley.browserd.v1.ObserveOptionsR\aoptions\"U\n" +
	"\x0fObserveResponse\x12B\n" +
	"\vobservation\x18\x01 \x01(\v2 .buckley.browserd.v1.ObservationR\vobservation\"A\n" +
	"\n" +
	"ActRequest\x123\n" +
	"\x06action\x18\x01 \x01(\v2\x1b.buckley.browserd.v1.ActionR\x06action\"H\n" +
	"\vActResponse\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.buckley.browserd.v1.ActionResultR\x06result\"\x15\n" +
	"\x13CloseSessionRequest\".\n" +
	"\x14CloseSessionResponse\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed\"V\n" +
	"\x16StreamSubscribeRequest\x12<\n" +
	"\aoptions\x18\x01 \x01(\v2\".buckley.browserd.v1.StreamOptionsR\aoptions\"9\n" +
	"\x17StreamSubscribeResponse\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\bR\n" +
	"subscribed\"c\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rstate_version\x18\x02 \x01(\x04R\fstateVersion\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xed\x02\n" +
	"\rSessionConfig\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vinitial_url\x18\x02 \x01(\tR\n" +
	"initialUrl\x129\n" +
	"\bviewport\x18\x03 \x01(\v2\x1d.buckley.browserd.v1.ViewportR\bviewport\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\a \x01(\rR\tframeRate\x12+\n" +
	"\x11network_allowlist\x18\b \x03(\tR\x10networkAllowlist\x12B\n" +
	"\tclipboard\x18\t \x01(\v2$.buckley.browserd.v1.ClipboardPolicyR\tclipboard\"h\n" +
	"\bViewport\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12.\n" +
	"\x13device_scale_factor\x18\x03 \x01(\x01R\x11deviceScaleFactor\"\xcd\x01\n" +
	"\x0fClipboardPolicy\x126\n" +
	"\x04mode\x18\x01 \x01(\x0e2\".buckley.browserd.v1.ClipboardModeR\x04mode\x12\x1d\n" +
	"\n" +
	"allow_read\x18\x02 \x01(\bR\tallowRead\x12\x1f\n" +
	"\vallow_write\x18\x03 \x01(\bR\n" +
	"allowWrite\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\rR\bmaxBytes\x12%\n" +
	"\x0eread_allowlist\x18\x05 \x03(\tR\rreadAllowlist\"\xc6\x01\n" +
	"\x0eObserveOptions\x12#\n" +
	"\rinclude_frame\x18\x01 \x01(\bR\fincludeFrame\x120\n" +
	"\x14include_dom_snapshot\x18\x02 \x01(\bR\x12includeDomSnapshot\x123\n" +
	"\x15include_accessibility\x18\x03 \x01(\bR\x14includeAccessibility\x12(\n" +
	"\x10include_hit_test\x18\x04 \x01(\bR\x0eincludeHitTest\"\xeb\x01\n" +
	"\rStreamOptions\x12%\n" +
	"\x0einclude_frames\x18\x01 \x01(\bR\rincludeFrames\x12*\n" +
	"\x11include_dom_diffs\x18\x02 \x01(\bR\x0fincludeDomDiffs\x12>\n" +
	"\x1binclude_accessibility_diffs\x18\x03 \x01(\bR\x19includeAccessibilityDiffs\x12(\n" +
	"\x10include_hit_test\x18\x04 \x01(\bR\x0eincludeHitTest\x12\x1d\n" +
	"\n" +
	"target_fps\x18\x05 \x01(\rR\ttargetFps\"\xd4\x02\n" +
	"\vObservation\x12#\n" +
	"\rstate_version\x18\x01 \x01(\x04R\fstateVersion\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x120\n" +
	"\x05frame\x18\x04 \x01(\v2\x1a.buckley.browserd.v1.FrameR\x05frame\x12!\n" +
	"\fdom_snapshot\x18\x05 \x01(\fR\vdomSnapshot\x12-\n" +
	"\x12accessibility_tree\x18\x06 \x01(\fR\x11accessibilityTree\x12:\n" +
	"\bhit_test\x18\a \x01(\v2\x1f.buckley.browserd.v1.HitTestMapR\ahitTest\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe2\x01\n" +
	"\x05Frame\x12#\n" +
	"\rstate_version\x18\x01 \x01(\x04R\fstateVersion\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x128\n" +
	"\x06format\x18\x04 \x01(\x0e2 .buckley.browserd.v1.FrameFormatR\x06format\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"t\n" +
	"\n" +
	"HitTestMap\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x128\n" +
	"\aregions\x18\x03 \x03(\v2\x1e.buckley.browserd.v1.HitRegionR\aregions\"W\n" +
	"\tHitRegion\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x121\n" +
	"\x06bounds\x18\x02 \x01(\v2\x19.buckley.browserd.v1.RectR\x06bounds\"P\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xce\x02\n" +
	"\x06Action\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.buckley.browserd.v1.ActionTypeR\x04type\x124\n" +
	"\x16expected_state_version\x18\x02 \x01(\x04R\x14expectedStateVersion\x129\n" +
	"\x06target\x18\x03 \x01(\v2!.buckley.browserd.v1.ActionTargetR\x06target\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x128\n" +
	"\x06scroll\x18\x06 \x01(\v2 .buckley.browserd.v1.ScrollDeltaR\x06scroll\x12>\n" +
	"\tmodifiers\x18\a \x03(\x0e2 .buckley.browserd.v1.KeyModifierR\tmodifiers\"Y\n" +
	"\fActionTarget\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x120\n" +
	"\x05point\x18\x02 \x01(\v2\x1a.buckley.browserd.v1.PointR\x05point\"^\n" +
	"\vScrollDelta\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x123\n" +
	"\x04unit\x18\x03 \x01(\x0e2\x1f.buckley.browserd.v1.ScrollUnitR\x04unit\"\xae\x01\n" +
	"\fActionResult\x12#\n" +
	"\rstate_version\x18\x01 \x01(\x04R\fstateVersion\x12B\n" +
	"\vobservation\x18\x02 \x01(\v2 .buckley.browserd.v1.ObservationR\vobservation\x125\n" +
	"\aeffects\x18\x03 \x03(\v2\x1b.buckley.browserd.v1.EffectR\aeffects\"k\n" +
	"\x06Effect\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xde\x02\n" +
	"\vStreamEvent\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.buckley.browserd.v1.StreamEventTypeR\x04type\x12#\n" +
	"\rstate_version\x18\x02 \x01(\x04R\fstateVersion\x120\n" +
	"\x05frame\x18\x03 \x01(\v2\x1a.buckley.browserd.v1.FrameR\x05frame\x12\x19\n" +
	"\bdom_diff\x18\x04 \x01(\fR\adomDiff\x12-\n" +
	"\x12accessibility_diff\x18\x05 \x01(\fR\x11accessibilityDiff\x12:\n" +
	"\bhit_test\x18\x06 \x01(\v2\x1f.buckley.browserd.v1.HitTestMapR\ahitTest\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*d\n" +
	"\rClipboardMode\x12\x1e\n" +
	"\x1aCLIPBOARD_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CLIPBOARD_MODE_VIRTUAL\x10\x01\x12\x17\n" +
	"\x13CLIPBOARD_MODE_HOST\x10\x02*o\n" +
	"\vFrameFormat\x12\x1c\n" +
	"\x18FRAME_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FRAME_FORMAT_PNG\x10\x01\x12\x15\n" +
	"\x11FRAME_FORMAT_JPEG\x10\x02\x12\x15\n" +
	"\x11FRAME_FORMAT_WEBP\x10\x03*X\n" +
	"\n" +
	"ScrollUnit\x12\x1b\n" +
	"\x17SCROLL_UNIT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SCROLL_UNIT_PIXELS\x10\x01\x12\x15\n" +
	"\x11SCROLL_UNIT_LINES\x10\x02*\xf2\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_TYPE_CLICK\x10\x01\x12\x14\n" +
	"\x10ACTION_TYPE_TYPE\x10\x02\x12\x16\n" +
	"\x12ACTION_TYPE_SCROLL\x10\x03\x12\x15\n" +
	"\x11ACTION_TYPE_HOVER\x10\x04\x12\x13\n" +
	"\x0fACTION_TYPE_KEY\x10\x05\x12\x15\n" +
	"\x11ACTION_TYPE_FOCUS\x10\x06\x12\x1e\n" +
	"\x1aACTION_TYPE_CLIPBOARD_READ\x10\a\x12\x1f\n" +
	"\x1bACTION_TYPE_CLIPBOARD_WRITE\x10\b*\x87\x01\n" +
	"\vKeyModifier\x12\x1c\n" +
	"\x18KEY_MODIFIER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KEY_MODIFIER_SHIFT\x10\x01\x12\x14\n" +
	"\x10KEY_MODIFIER_ALT\x10\x02\x12\x15\n" +
	"\x11KEY_MODIFIER_CTRL\x10\x03\x12\x15\n" +
	"\x11KEY_MODIFIER_META\x10\x04*\xbb\x01\n" +
	"\x0fStreamEventType\x12!\n" +
	"\x1dSTREAM_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_EVENT_TYPE_FRAME\x10\x01\x12\x1e\n" +
	"\x1aSTREAM_EVENT_TYPE_DOM_DIFF\x10\x02\x12(\n" +
	"$STREAM_EVENT_TYPE_ACCESSIBILITY_DIFF\x10\x03\x12\x1e\n" +
	"\x1aSTREAM_EVENT_TYPE_HIT_TEST\x10\x04BJZHgithub.com/odvcencio/buckley/pkg/browser/adapters/servo/proto;browserdpbb\x06proto3"

var (
	file_browserd_proto_rawDescOnce sync.Once
	file_browserd_proto_rawDescData []byte
)

func file_browserd_proto_rawDescGZIP() []byte {
	file_browserd_proto_rawDescOnce.Do(func() {
		file_browserd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_browserd_proto_rawDesc), len(file_browserd_proto_rawDesc)))
	})
	return file_browserd_proto_rawDescData
}

var file_browserd_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_browserd_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_browserd_proto_goTypes = []any{
	(ClipboardMode)(0),              // 0: buckley.browserd.v1.ClipboardMode
	(FrameFormat)(0),                // 1: buckley.browserd.v1.FrameFormat
	(ScrollUnit)(0),                 // 2: buckley.browserd.v1.ScrollUnit
	(ActionType)(0),                 // 3: buckley.browserd.v1.ActionType
	(KeyModifier)(0),                // 4: buckley.browserd.v1.KeyModifier
	(StreamEventType)(0),            // 5: buckley.browserd.v1.StreamEventType
	(*Envelope)(nil),                // 6: buckley.browserd.v1.Envelope
	(*Error)(nil),                   // 7: buckley.browserd.v1.Error
	(*Request)(nil),                 // 8: buckley.browserd.v1.Request
	(*Response)(nil),                // 9: buckley.browserd.v1.Response
	(*CreateSessionRequest)(nil),    // 10: buckley.browserd.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),   // 11: buckley.browserd.v1.CreateSessionResponse
	(*NavigateRequest)(nil),         // 12: buckley.browserd.v1.NavigateRequest
	(*NavigateResponse)(nil),        // 13: buckley.browserd.v1.NavigateResponse
	(*ObserveRequest)(nil),          // 14: buckley.browserd.v1.ObserveRequest
	(*ObserveResponse)(nil),         // 15: buckley.browserd.v1.ObserveResponse
	(*ActRequest)(nil),              // 16: buckley.browserd.v1.ActRequest
	(*ActResponse)(nil),             // 17: buckley.browserd.v1.ActResponse
	(*CloseSessionRequest)(nil),     // 18: buckley.browserd.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),    // 19: buckley.browserd.v1.CloseSessionResponse
	(*StreamSubscribeRequest)(nil),  // 20: buckley.browserd.v1.StreamSubscribeRequest
	(*StreamSubscribeResponse)(nil), // 21: buckley.browserd.v1.StreamSubscribeResponse
	(*SessionInfo)(nil),             // 22: buckley.browserd.v1.SessionInfo
	(*SessionConfig)(nil),           // 23: buckley.browserd.v1.SessionConfig
	(*Viewport)(nil),                // 24: buckley.browserd.v1.Viewport
	(*ClipboardPolicy)(nil),         // 25: buckley.browserd.v1.ClipboardPolicy
	(*ObserveOptions)(nil),          // 26: buckley.browserd.v1.ObserveOptions
	(*StreamOptions)(nil),           // 27: buckley.browserd.v1.StreamOptions
	(*Observation)(nil),             // 28: buckley.browserd.v1.Observation
	(*Frame)(nil),                   // 29: buckley.browserd.v1.Frame
	(*HitTestMap)(nil),              // 30: buckley.browserd.v1.HitTestMap
	(*HitRegion)(nil),               // 31: buckley.browserd.v1.HitRegion
	(*Rect)(nil),                    // 32: buckley.browserd.v1.Rect
	(*Point)(nil),                   // 33: buckley.browserd.v1.Point
	(*Action)(nil),                  // 34: buckley.browserd.v1.Action
	(*ActionTarget)(nil),            // 35: buckley.browserd.v1.ActionTarget
	(*ScrollDelta)(nil),             // 36: buckley.browserd.v1.ScrollDelta
	(*ActionResult)(nil),            // 37: buckley.browserd.v1.ActionResult
	(*Effect)(nil),                  // 38: buckley.browserd.v1.Effect
	(*StreamEvent)(nil),             // 39: buckley.browserd.v1.StreamEvent
	(*timestamppb.Timestamp)(nil),   // 40: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 41: google.protobuf.Struct
}
var file_browserd_proto_depIdxs = []int32{
	8,  // 0: buckley.browserd.v1.Envelope.request:type_name -> buckley.browserd.v1.Request
	9,  // 1: buckley.browserd.v1.Envelope.response:type_name -> buckley.browserd.v1.Response
	39, // 2: buckley.browserd.v1.Envelope.event:type_name -> buckley.browserd.v1.StreamEvent
	10, // 3: buckley.browserd.v1.Request.create_session:type_name -> buckley.browserd.v1.CreateSessionRequest
	12, // 4: buckley.browserd.v1.Request.navigate:type_name -> buckley.browserd.v1.NavigateRequest
	14, // 5: buckley.browserd.v1.Request.observe:type_name -> buckley.browserd.v1.ObserveRequest
	16, // 6: buckley.browserd.v1.Request.act:type_name -> buckley.browserd.v1.ActRequest
	18, // 7: buckley.browserd.v1.Request.close_session:type_name -> buckley.browserd.v1.CloseSessionRequest
	20, // 8: buckley.browserd.v1.Request.stream_subscribe:type_name -> buckley.browserd.v1.StreamSubscribeRequest
	7,  // 9: buckley.browserd.v1.Response.error:type_name -> buckley.browserd.v1.Error
	11, // 10: buckley.browserd.v1.Response.create_session:type_name -> buckley.browserd.v1.CreateSessionResponse
	13, // 11: buckley.browserd.v1.Response.navigate:type_name -> buckley.browserd.v1.NavigateResponse
	15, // 12: buckley.browserd.v1.Response.observe:type_name -> buckley.browserd.v1.ObserveResponse
	17, // 13: buckley.browserd.v1.Response.act:type_name -> buckley.browserd.v1.ActResponse
	19, // 14: buckley.browserd.v1.Response.close_session:type_name -> buckley.browserd.v1.CloseSessionResponse
	21, // 15: buckley.browserd.v1.Response.stream_subscribe:type_name -> buckley.browserd.v1.StreamSubscribeResponse
	23, // 16: buckley.browserd.v1.CreateSessionRequest.config:type_name -> buckley.browserd.v1.SessionConfig
	22, // 17: buckley.browserd.v1.CreateSessionResponse.session:type_name -> buckley.browserd.v1.SessionInfo
	28, // 18: buckley.browserd.v1.CreateSessionResponse.observation:type_name -> buckley.browserd.v1.Observation
	28, // 19: buckley.browserd.v1.NavigateResponse.observation:type_name -> buckley.browserd.v1.Observation
	26, // 20: buckley.browserd.v1.ObserveRequest.options:type_name -> buckley.browserd.v1.ObserveOptions
	28, // 21: buckley.browserd.v1.ObserveResponse.observation:type_name -> buckley.browserd.v1.Observation
	34, // 22: buckley.browserd.v1.ActRequest.action:type_name -> buckley.browserd.v1.Action
	37, // 23: buckley.browserd.v1.ActResponse.result:type_name -> buckley.browserd.v1.ActionResult
	27, // 24: buckley.browserd.v1.StreamSubscribeRequest.options:type_name -> buckley.browserd.v1.StreamOptions
	24, // 25: buckley.browserd.v1.SessionConfig.viewport:type_name -> buckley.browserd.v1.Viewport
	25, // 26: buckley.browserd.v1.SessionConfig.clipboard:type_name -> buckley.browserd.v1.ClipboardPolicy
	0,  // 27: buckley.browserd.v1.ClipboardPolicy.mode:type_name -> buckley.browserd.v1.ClipboardMode
	29, // 28: buckley.browserd.v1.Observation.frame:type_name -> buckley.browserd.v1.Frame
	30, // 29: buckley.browserd.v1.Observation.hit_test:type_name -> buckley.browserd.v1.HitTestMap
	40, // 30: buckley.browserd.v1.Observation.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 31: buckley.browserd.v1.Frame.format:type_name -> buckley.browserd.v1.FrameFormat
	40, // 32: buckley.browserd.v1.Frame.timestamp:type_name -> google.protobuf.Timestamp
	31, // 33: buckley.browserd.v1.HitTestMap.regions:type_name -> buckley.browserd.v1.HitRegion
	32, // 34: buckley.browserd.v1.HitRegion.bounds:type_name -> buckley.browserd.v1.Rect
	3,  // 35: buckley.browserd.v1.Action.type:type_name -> buckley.browserd.v1.ActionType
	35, // 36: buckley.browserd.v1.Action.target:type_name -> buckley.browserd.v1.ActionTarget
	36, // 37: buckley.browserd.v1.Action.scroll:type_name -> buckley.browserd.v1.ScrollDelta
	4,  // 38: buckley.browserd.v1.Action.modifiers:type_name -> buckley.browserd.v1.KeyModifier
	33, // 39: buckley.browserd.v1.ActionTarget.point:type_name -> buckley.browserd.v1.Point
	2,  // 40: buckley.browserd.v1.ScrollDelta.unit:type_name -> buckley.browserd.v1.ScrollUnit
	28, // 41: buckley.browserd.v1.ActionResult.observation:type_name -> buckley.browserd.v1.Observation
	38, // 42: buckley.browserd.v1.ActionResult.effects:type_name -> buckley.browserd.v1.Effect
	41, // 43: buckley.browserd.v1.Effect.metadata:type_name -> google.protobuf.Struct
	5,  // 44: buckley.browserd.v1.StreamEvent.type:type_name -> buckley.browserd.v1.StreamEventType
	29, // 45: buckley.browserd.v1.StreamEvent.frame:type_name -> buckley.browserd.v1.Frame
	30, // 46: buckley.browserd.v1.StreamEvent.hit_test:type_name -> buckley.browserd.v1.HitTestMap
	40, // 47: buckley.browserd.v1.StreamEvent.timestamp:type_name -> google.protobuf.Timestamp
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_browserd_proto_init() }
func file_browserd_proto_init() {
	if File_browserd_proto != nil {
		return
	}
	file_browserd_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Request)(nil),
		(*Envelope_Response)(nil),
		(*Envelope_Event)(nil),
	}
	file_browserd_proto_msgTypes[2].OneofWrappers = []any{
		(*Request_CreateSession)(nil),
		(*Request_Navigate)(nil),
		(*Request_Observe)(nil),
		(*Request_Act)(nil),
		(*Request_CloseSession)(nil),
		(*Request_StreamSubscribe)(nil),
	}
	file_browserd_proto_msgTypes[3].OneofWrappers = []any{
		(*Response_CreateSession)(nil),
		(*Response_Navigate)(nil),
		(*Response_Observe)(nil),
		(*Response_Act)(nil),
		(*Response_CloseSession)(nil),
		(*Response_StreamSubscribe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_browserd_proto_rawDesc), len(file_browserd_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_browserd_proto_goTypes,
		DependencyIndexes: file_browserd_proto_depIdxs,
		EnumInfos:         file_browserd_proto_enumTypes,
		MessageInfos:      file_browserd_proto_msgTypes,
	}.Build()
	File_browserd_proto = out.File
	file_browserd_proto_goTypes = nil
	file_browserd_proto_depIdxs = nil
}
