// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/cost (interfaces: costStore,CostCalculator)
//
// Generated by this command:
//
//	mockgen -package=cost -destination=pkg/cost/cost_mocks_test.go github.com/odvcencio/buckley/pkg/cost costStore,CostCalculator
//

// Package cost is a generated GoMock package.
package cost

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	storage "github.com/odvcencio/buckley/pkg/storage"
)

// MockcostStore is a mock of costStore interface.
type MockcostStore struct {
	ctrl     *gomock.Controller
	recorder *MockcostStoreMockRecorder
	isgomock struct{}
}

// MockcostStoreMockRecorder is the mock recorder for MockcostStore.
type MockcostStoreMockRecorder struct {
	mock *MockcostStore
}

// NewMockcostStore creates a new mock instance.
func NewMockcostStore(ctrl *gomock.Controller) *MockcostStore {
	mock := &MockcostStore{ctrl: ctrl}
	mock.recorder = &MockcostStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcostStore) EXPECT() *MockcostStoreMockRecorder {
	return m.recorder
}

// GetDailyCost mocks base method.
func (m *MockcostStore) GetDailyCost() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyCost")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyCost indicates an expected call of GetDailyCost.
func (mr *MockcostStoreMockRecorder) GetDailyCost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyCost", reflect.TypeOf((*MockcostStore)(nil).GetDailyCost))
}

// GetMonthlyCost mocks base method.
func (m *MockcostStore) GetMonthlyCost() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyCost")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyCost indicates an expected call of GetMonthlyCost.
func (mr *MockcostStoreMockRecorder) GetMonthlyCost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyCost", reflect.TypeOf((*MockcostStore)(nil).GetMonthlyCost))
}

// GetSession mocks base method.
func (m *MockcostStore) GetSession(sessionID string) (*storage.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*storage.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockcostStoreMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockcostStore)(nil).GetSession), sessionID)
}

// SaveAPICall mocks base method.
func (m *MockcostStore) SaveAPICall(call *storage.APICall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAPICall", call)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAPICall indicates an expected call of SaveAPICall.
func (mr *MockcostStoreMockRecorder) SaveAPICall(call any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAPICall", reflect.TypeOf((*MockcostStore)(nil).SaveAPICall), call)
}

// MockCostCalculator is a mock of CostCalculator interface.
type MockCostCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCostCalculatorMockRecorder
	isgomock struct{}
}

// MockCostCalculatorMockRecorder is the mock recorder for MockCostCalculator.
type MockCostCalculatorMockRecorder struct {
	mock *MockCostCalculator
}

// NewMockCostCalculator creates a new mock instance.
func NewMockCostCalculator(ctrl *gomock.Controller) *MockCostCalculator {
	mock := &MockCostCalculator{ctrl: ctrl}
	mock.recorder = &MockCostCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostCalculator) EXPECT() *MockCostCalculatorMockRecorder {
	return m.recorder
}

// CalculateCostFromTokens mocks base method.
func (m *MockCostCalculator) CalculateCostFromTokens(modelID string, promptTokens, completionTokens int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateCostFromTokens", modelID, promptTokens, completionTokens)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateCostFromTokens indicates an expected call of CalculateCostFromTokens.
func (mr *MockCostCalculatorMockRecorder) CalculateCostFromTokens(modelID, promptTokens, completionTokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateCostFromTokens", reflect.TypeOf((*MockCostCalculator)(nil).CalculateCostFromTokens), modelID, promptTokens, completionTokens)
}
