// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/session (interfaces: gitCommandRunner)
//
// Generated by this command:
//
//	mockgen -package=session -destination=mock_git_runner_test.go github.com/odvcencio/buckley/pkg/session gitCommandRunner
//

// Package session is a generated GoMock package.
package session

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockgitCommandRunner is a mock of gitCommandRunner interface.
type MockgitCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockgitCommandRunnerMockRecorder
	isgomock struct{}
}

// MockgitCommandRunnerMockRecorder is the mock recorder for MockgitCommandRunner.
type MockgitCommandRunnerMockRecorder struct {
	mock *MockgitCommandRunner
}

// NewMockgitCommandRunner creates a new mock instance.
func NewMockgitCommandRunner(ctrl *gomock.Controller) *MockgitCommandRunner {
	mock := &MockgitCommandRunner{ctrl: ctrl}
	mock.recorder = &MockgitCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgitCommandRunner) EXPECT() *MockgitCommandRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockgitCommandRunner) Run(ctx context.Context, dir string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dir}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockgitCommandRunnerMockRecorder) Run(ctx, dir any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dir}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockgitCommandRunner)(nil).Run), varargs...)
}
