// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/github (interfaces: commandRunner)
//
// Generated by this command:
//
//	mockgen -package=github -destination=mock_runner_test.go github.com/odvcencio/buckley/pkg/github commandRunner
//

// Package github is a generated GoMock package.
package github

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockcommandRunner is a mock of commandRunner interface.
type MockcommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockcommandRunnerMockRecorder
	isgomock struct{}
}

// MockcommandRunnerMockRecorder is the mock recorder for MockcommandRunner.
type MockcommandRunnerMockRecorder struct {
	mock *MockcommandRunner
}

// NewMockcommandRunner creates a new mock instance.
func NewMockcommandRunner(ctrl *gomock.Controller) *MockcommandRunner {
	mock := &MockcommandRunner{ctrl: ctrl}
	mock.recorder = &MockcommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommandRunner) EXPECT() *MockcommandRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockcommandRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockcommandRunnerMockRecorder) Run(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockcommandRunner)(nil).Run), varargs...)
}
