// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ipc.proto

package ipcpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/odvcencio/buckley/pkg/ipc/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BuckleyIPCName is the fully-qualified name of the BuckleyIPC service.
	BuckleyIPCName = "buckley.ipc.v1.BuckleyIPC"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BuckleyIPCSubscribeProcedure is the fully-qualified name of the BuckleyIPC's Subscribe RPC.
	BuckleyIPCSubscribeProcedure = "/buckley.ipc.v1.BuckleyIPC/Subscribe"
	// BuckleyIPCSendCommandProcedure is the fully-qualified name of the BuckleyIPC's SendCommand RPC.
	BuckleyIPCSendCommandProcedure = "/buckley.ipc.v1.BuckleyIPC/SendCommand"
	// BuckleyIPCListSessionsProcedure is the fully-qualified name of the BuckleyIPC's ListSessions RPC.
	BuckleyIPCListSessionsProcedure = "/buckley.ipc.v1.BuckleyIPC/ListSessions"
	// BuckleyIPCGetSessionProcedure is the fully-qualified name of the BuckleyIPC's GetSession RPC.
	BuckleyIPCGetSessionProcedure = "/buckley.ipc.v1.BuckleyIPC/GetSession"
	// BuckleyIPCCreateHeadlessSessionProcedure is the fully-qualified name of the BuckleyIPC's
	// CreateHeadlessSession RPC.
	BuckleyIPCCreateHeadlessSessionProcedure = "/buckley.ipc.v1.BuckleyIPC/CreateHeadlessSession"
	// BuckleyIPCDeleteHeadlessSessionProcedure is the fully-qualified name of the BuckleyIPC's
	// DeleteHeadlessSession RPC.
	BuckleyIPCDeleteHeadlessSessionProcedure = "/buckley.ipc.v1.BuckleyIPC/DeleteHeadlessSession"
	// BuckleyIPCListHeadlessSessionsProcedure is the fully-qualified name of the BuckleyIPC's
	// ListHeadlessSessions RPC.
	BuckleyIPCListHeadlessSessionsProcedure = "/buckley.ipc.v1.BuckleyIPC/ListHeadlessSessions"
	// BuckleyIPCListPlansProcedure is the fully-qualified name of the BuckleyIPC's ListPlans RPC.
	BuckleyIPCListPlansProcedure = "/buckley.ipc.v1.BuckleyIPC/ListPlans"
	// BuckleyIPCGetPlanProcedure is the fully-qualified name of the BuckleyIPC's GetPlan RPC.
	BuckleyIPCGetPlanProcedure = "/buckley.ipc.v1.BuckleyIPC/GetPlan"
	// BuckleyIPCListProjectsProcedure is the fully-qualified name of the BuckleyIPC's ListProjects RPC.
	BuckleyIPCListProjectsProcedure = "/buckley.ipc.v1.BuckleyIPC/ListProjects"
	// BuckleyIPCCreateProjectProcedure is the fully-qualified name of the BuckleyIPC's CreateProject
	// RPC.
	BuckleyIPCCreateProjectProcedure = "/buckley.ipc.v1.BuckleyIPC/CreateProject"
	// BuckleyIPCListPersonasProcedure is the fully-qualified name of the BuckleyIPC's ListPersonas RPC.
	BuckleyIPCListPersonasProcedure = "/buckley.ipc.v1.BuckleyIPC/ListPersonas"
	// BuckleyIPCWorkflowActionProcedure is the fully-qualified name of the BuckleyIPC's WorkflowAction
	// RPC.
	BuckleyIPCWorkflowActionProcedure = "/buckley.ipc.v1.BuckleyIPC/WorkflowAction"
	// BuckleyIPCRegisterAgentProcedure is the fully-qualified name of the BuckleyIPC's RegisterAgent
	// RPC.
	BuckleyIPCRegisterAgentProcedure = "/buckley.ipc.v1.BuckleyIPC/RegisterAgent"
	// BuckleyIPCReportAgentResultProcedure is the fully-qualified name of the BuckleyIPC's
	// ReportAgentResult RPC.
	BuckleyIPCReportAgentResultProcedure = "/buckley.ipc.v1.BuckleyIPC/ReportAgentResult"
	// BuckleyIPCAgentHeartbeatProcedure is the fully-qualified name of the BuckleyIPC's AgentHeartbeat
	// RPC.
	BuckleyIPCAgentHeartbeatProcedure = "/buckley.ipc.v1.BuckleyIPC/AgentHeartbeat"
	// BuckleyIPCListAgentsProcedure is the fully-qualified name of the BuckleyIPC's ListAgents RPC.
	BuckleyIPCListAgentsProcedure = "/buckley.ipc.v1.BuckleyIPC/ListAgents"
	// BuckleyIPCListPendingApprovalsProcedure is the fully-qualified name of the BuckleyIPC's
	// ListPendingApprovals RPC.
	BuckleyIPCListPendingApprovalsProcedure = "/buckley.ipc.v1.BuckleyIPC/ListPendingApprovals"
	// BuckleyIPCApproveToolCallProcedure is the fully-qualified name of the BuckleyIPC's
	// ApproveToolCall RPC.
	BuckleyIPCApproveToolCallProcedure = "/buckley.ipc.v1.BuckleyIPC/ApproveToolCall"
	// BuckleyIPCRejectToolCallProcedure is the fully-qualified name of the BuckleyIPC's RejectToolCall
	// RPC.
	BuckleyIPCRejectToolCallProcedure = "/buckley.ipc.v1.BuckleyIPC/RejectToolCall"
	// BuckleyIPCGetApprovalPolicyProcedure is the fully-qualified name of the BuckleyIPC's
	// GetApprovalPolicy RPC.
	BuckleyIPCGetApprovalPolicyProcedure = "/buckley.ipc.v1.BuckleyIPC/GetApprovalPolicy"
	// BuckleyIPCUpdateApprovalPolicyProcedure is the fully-qualified name of the BuckleyIPC's
	// UpdateApprovalPolicy RPC.
	BuckleyIPCUpdateApprovalPolicyProcedure = "/buckley.ipc.v1.BuckleyIPC/UpdateApprovalPolicy"
	// BuckleyIPCGetAuditLogProcedure is the fully-qualified name of the BuckleyIPC's GetAuditLog RPC.
	BuckleyIPCGetAuditLogProcedure = "/buckley.ipc.v1.BuckleyIPC/GetAuditLog"
	// BuckleyIPCSubscribePushProcedure is the fully-qualified name of the BuckleyIPC's SubscribePush
	// RPC.
	BuckleyIPCSubscribePushProcedure = "/buckley.ipc.v1.BuckleyIPC/SubscribePush"
	// BuckleyIPCUnsubscribePushProcedure is the fully-qualified name of the BuckleyIPC's
	// UnsubscribePush RPC.
	BuckleyIPCUnsubscribePushProcedure = "/buckley.ipc.v1.BuckleyIPC/UnsubscribePush"
	// BuckleyIPCGetVAPIDPublicKeyProcedure is the fully-qualified name of the BuckleyIPC's
	// GetVAPIDPublicKey RPC.
	BuckleyIPCGetVAPIDPublicKeyProcedure = "/buckley.ipc.v1.BuckleyIPC/GetVAPIDPublicKey"
)

// BuckleyIPCClient is a client for the buckley.ipc.v1.BuckleyIPC service.
type BuckleyIPCClient interface {
	// Subscribe opens a server-streaming connection for real-time events.
	// Used by web UI, CLI watchers, and monitoring tools.
	Subscribe(context.Context, *connect.Request[proto.SubscribeRequest]) (*connect.ServerStreamForClient[proto.Event], error)
	// SendCommand dispatches user input or slash commands to a session.
	SendCommand(context.Context, *connect.Request[proto.CommandRequest]) (*connect.Response[proto.CommandResponse], error)
	// ListSessions returns all active and recent sessions.
	ListSessions(context.Context, *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error)
	// GetSession returns detailed session state including messages and todos.
	GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.SessionDetail], error)
	// CreateHeadlessSession spawns an isolated session on the server.
	CreateHeadlessSession(context.Context, *connect.Request[proto.CreateHeadlessRequest]) (*connect.Response[proto.HeadlessSession], error)
	// DeleteHeadlessSession terminates and cleans up a headless session.
	DeleteHeadlessSession(context.Context, *connect.Request[proto.DeleteHeadlessRequest]) (*connect.Response[emptypb.Empty], error)
	// ListHeadlessSessions returns all running headless sessions.
	ListHeadlessSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.HeadlessSessionList], error)
	// ListPlans returns all available plans.
	ListPlans(context.Context, *connect.Request[proto.ListPlansRequest]) (*connect.Response[proto.ListPlansResponse], error)
	// GetPlan returns detailed plan information including tasks.
	GetPlan(context.Context, *connect.Request[proto.GetPlanRequest]) (*connect.Response[proto.Plan], error)
	// ListProjects returns all known projects.
	ListProjects(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.ProjectList], error)
	// CreateProject registers a new project.
	CreateProject(context.Context, *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.Project], error)
	// ListPersonas returns available AI personas.
	ListPersonas(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.PersonaList], error)
	// WorkflowAction triggers plan/execute/pause/resume operations.
	WorkflowAction(context.Context, *connect.Request[proto.WorkflowActionRequest]) (*connect.Response[proto.WorkflowActionResponse], error)
	// RegisterAgent connects a host agent to the server.
	// The agent receives commands via the returned stream.
	RegisterAgent(context.Context, *connect.Request[proto.RegisterAgentRequest]) (*connect.ServerStreamForClient[proto.AgentCommand], error)
	// ReportAgentResult sends execution results back to the server.
	ReportAgentResult(context.Context, *connect.Request[proto.AgentResult]) (*connect.Response[emptypb.Empty], error)
	// AgentHeartbeat keeps the agent connection alive and reports status.
	AgentHeartbeat(context.Context, *connect.Request[proto.AgentHeartbeatRequest]) (*connect.Response[proto.AgentHeartbeatResponse], error)
	// ListAgents returns all connected host agents.
	ListAgents(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.AgentList], error)
	// ListPendingApprovals returns pending tool call approvals for a session.
	ListPendingApprovals(context.Context, *connect.Request[proto.ListPendingApprovalsRequest]) (*connect.Response[proto.PendingApprovalsList], error)
	// ApproveToolCall approves a pending tool call.
	ApproveToolCall(context.Context, *connect.Request[proto.ApproveToolCallRequest]) (*connect.Response[proto.ApproveToolCallResponse], error)
	// RejectToolCall rejects a pending tool call.
	RejectToolCall(context.Context, *connect.Request[proto.RejectToolCallRequest]) (*connect.Response[proto.RejectToolCallResponse], error)
	// GetApprovalPolicy returns the active approval policy.
	GetApprovalPolicy(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.ApprovalPolicy], error)
	// UpdateApprovalPolicy updates the approval policy configuration.
	UpdateApprovalPolicy(context.Context, *connect.Request[proto.UpdateApprovalPolicyRequest]) (*connect.Response[proto.ApprovalPolicy], error)
	// GetAuditLog returns the tool execution audit log for a session.
	GetAuditLog(context.Context, *connect.Request[proto.GetAuditLogRequest]) (*connect.Response[proto.AuditLogResponse], error)
	// SubscribePush registers a browser for push notifications.
	SubscribePush(context.Context, *connect.Request[proto.PushSubscriptionRequest]) (*connect.Response[proto.PushSubscriptionResponse], error)
	// UnsubscribePush removes a push subscription.
	UnsubscribePush(context.Context, *connect.Request[proto.UnsubscribePushRequest]) (*connect.Response[emptypb.Empty], error)
	// GetVAPIDPublicKey returns the server's VAPID public key for Web Push.
	GetVAPIDPublicKey(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.VAPIDPublicKeyResponse], error)
}

// NewBuckleyIPCClient constructs a client for the buckley.ipc.v1.BuckleyIPC service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBuckleyIPCClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BuckleyIPCClient {
	baseURL = strings.TrimRight(baseURL, "/")
	buckleyIPCMethods := proto.File_ipc_proto.Services().ByName("BuckleyIPC").Methods()
	return &buckleyIPCClient{
		subscribe: connect.NewClient[proto.SubscribeRequest, proto.Event](
			httpClient,
			baseURL+BuckleyIPCSubscribeProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		sendCommand: connect.NewClient[proto.CommandRequest, proto.CommandResponse](
			httpClient,
			baseURL+BuckleyIPCSendCommandProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("SendCommand")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[proto.ListSessionsRequest, proto.ListSessionsResponse](
			httpClient,
			baseURL+BuckleyIPCListSessionsProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[proto.GetSessionRequest, proto.SessionDetail](
			httpClient,
			baseURL+BuckleyIPCGetSessionProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		createHeadlessSession: connect.NewClient[proto.CreateHeadlessRequest, proto.HeadlessSession](
			httpClient,
			baseURL+BuckleyIPCCreateHeadlessSessionProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("CreateHeadlessSession")),
			connect.WithClientOptions(opts...),
		),
		deleteHeadlessSession: connect.NewClient[proto.DeleteHeadlessRequest, emptypb.Empty](
			httpClient,
			baseURL+BuckleyIPCDeleteHeadlessSessionProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("DeleteHeadlessSession")),
			connect.WithClientOptions(opts...),
		),
		listHeadlessSessions: connect.NewClient[emptypb.Empty, proto.HeadlessSessionList](
			httpClient,
			baseURL+BuckleyIPCListHeadlessSessionsProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListHeadlessSessions")),
			connect.WithClientOptions(opts...),
		),
		listPlans: connect.NewClient[proto.ListPlansRequest, proto.ListPlansResponse](
			httpClient,
			baseURL+BuckleyIPCListPlansProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListPlans")),
			connect.WithClientOptions(opts...),
		),
		getPlan: connect.NewClient[proto.GetPlanRequest, proto.Plan](
			httpClient,
			baseURL+BuckleyIPCGetPlanProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("GetPlan")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[emptypb.Empty, proto.ProjectList](
			httpClient,
			baseURL+BuckleyIPCListProjectsProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[proto.CreateProjectRequest, proto.Project](
			httpClient,
			baseURL+BuckleyIPCCreateProjectProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		listPersonas: connect.NewClient[emptypb.Empty, proto.PersonaList](
			httpClient,
			baseURL+BuckleyIPCListPersonasProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListPersonas")),
			connect.WithClientOptions(opts...),
		),
		workflowAction: connect.NewClient[proto.WorkflowActionRequest, proto.WorkflowActionResponse](
			httpClient,
			baseURL+BuckleyIPCWorkflowActionProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("WorkflowAction")),
			connect.WithClientOptions(opts...),
		),
		registerAgent: connect.NewClient[proto.RegisterAgentRequest, proto.AgentCommand](
			httpClient,
			baseURL+BuckleyIPCRegisterAgentProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("RegisterAgent")),
			connect.WithClientOptions(opts...),
		),
		reportAgentResult: connect.NewClient[proto.AgentResult, emptypb.Empty](
			httpClient,
			baseURL+BuckleyIPCReportAgentResultProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ReportAgentResult")),
			connect.WithClientOptions(opts...),
		),
		agentHeartbeat: connect.NewClient[proto.AgentHeartbeatRequest, proto.AgentHeartbeatResponse](
			httpClient,
			baseURL+BuckleyIPCAgentHeartbeatProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("AgentHeartbeat")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[emptypb.Empty, proto.AgentList](
			httpClient,
			baseURL+BuckleyIPCListAgentsProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		listPendingApprovals: connect.NewClient[proto.ListPendingApprovalsRequest, proto.PendingApprovalsList](
			httpClient,
			baseURL+BuckleyIPCListPendingApprovalsProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ListPendingApprovals")),
			connect.WithClientOptions(opts...),
		),
		approveToolCall: connect.NewClient[proto.ApproveToolCallRequest, proto.ApproveToolCallResponse](
			httpClient,
			baseURL+BuckleyIPCApproveToolCallProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("ApproveToolCall")),
			connect.WithClientOptions(opts...),
		),
		rejectToolCall: connect.NewClient[proto.RejectToolCallRequest, proto.RejectToolCallResponse](
			httpClient,
			baseURL+BuckleyIPCRejectToolCallProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("RejectToolCall")),
			connect.WithClientOptions(opts...),
		),
		getApprovalPolicy: connect.NewClient[emptypb.Empty, proto.ApprovalPolicy](
			httpClient,
			baseURL+BuckleyIPCGetApprovalPolicyProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("GetApprovalPolicy")),
			connect.WithClientOptions(opts...),
		),
		updateApprovalPolicy: connect.NewClient[proto.UpdateApprovalPolicyRequest, proto.ApprovalPolicy](
			httpClient,
			baseURL+BuckleyIPCUpdateApprovalPolicyProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("UpdateApprovalPolicy")),
			connect.WithClientOptions(opts...),
		),
		getAuditLog: connect.NewClient[proto.GetAuditLogRequest, proto.AuditLogResponse](
			httpClient,
			baseURL+BuckleyIPCGetAuditLogProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("GetAuditLog")),
			connect.WithClientOptions(opts...),
		),
		subscribePush: connect.NewClient[proto.PushSubscriptionRequest, proto.PushSubscriptionResponse](
			httpClient,
			baseURL+BuckleyIPCSubscribePushProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("SubscribePush")),
			connect.WithClientOptions(opts...),
		),
		unsubscribePush: connect.NewClient[proto.UnsubscribePushRequest, emptypb.Empty](
			httpClient,
			baseURL+BuckleyIPCUnsubscribePushProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("UnsubscribePush")),
			connect.WithClientOptions(opts...),
		),
		getVAPIDPublicKey: connect.NewClient[emptypb.Empty, proto.VAPIDPublicKeyResponse](
			httpClient,
			baseURL+BuckleyIPCGetVAPIDPublicKeyProcedure,
			connect.WithSchema(buckleyIPCMethods.ByName("GetVAPIDPublicKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// buckleyIPCClient implements BuckleyIPCClient.
type buckleyIPCClient struct {
	subscribe             *connect.Client[proto.SubscribeRequest, proto.Event]
	sendCommand           *connect.Client[proto.CommandRequest, proto.CommandResponse]
	listSessions          *connect.Client[proto.ListSessionsRequest, proto.ListSessionsResponse]
	getSession            *connect.Client[proto.GetSessionRequest, proto.SessionDetail]
	createHeadlessSession *connect.Client[proto.CreateHeadlessRequest, proto.HeadlessSession]
	deleteHeadlessSession *connect.Client[proto.DeleteHeadlessRequest, emptypb.Empty]
	listHeadlessSessions  *connect.Client[emptypb.Empty, proto.HeadlessSessionList]
	listPlans             *connect.Client[proto.ListPlansRequest, proto.ListPlansResponse]
	getPlan               *connect.Client[proto.GetPlanRequest, proto.Plan]
	listProjects          *connect.Client[emptypb.Empty, proto.ProjectList]
	createProject         *connect.Client[proto.CreateProjectRequest, proto.Project]
	listPersonas          *connect.Client[emptypb.Empty, proto.PersonaList]
	workflowAction        *connect.Client[proto.WorkflowActionRequest, proto.WorkflowActionResponse]
	registerAgent         *connect.Client[proto.RegisterAgentRequest, proto.AgentCommand]
	reportAgentResult     *connect.Client[proto.AgentResult, emptypb.Empty]
	agentHeartbeat        *connect.Client[proto.AgentHeartbeatRequest, proto.AgentHeartbeatResponse]
	listAgents            *connect.Client[emptypb.Empty, proto.AgentList]
	listPendingApprovals  *connect.Client[proto.ListPendingApprovalsRequest, proto.PendingApprovalsList]
	approveToolCall       *connect.Client[proto.ApproveToolCallRequest, proto.ApproveToolCallResponse]
	rejectToolCall        *connect.Client[proto.RejectToolCallRequest, proto.RejectToolCallResponse]
	getApprovalPolicy     *connect.Client[emptypb.Empty, proto.ApprovalPolicy]
	updateApprovalPolicy  *connect.Client[proto.UpdateApprovalPolicyRequest, proto.ApprovalPolicy]
	getAuditLog           *connect.Client[proto.GetAuditLogRequest, proto.AuditLogResponse]
	subscribePush         *connect.Client[proto.PushSubscriptionRequest, proto.PushSubscriptionResponse]
	unsubscribePush       *connect.Client[proto.UnsubscribePushRequest, emptypb.Empty]
	getVAPIDPublicKey     *connect.Client[emptypb.Empty, proto.VAPIDPublicKeyResponse]
}

// Subscribe calls buckley.ipc.v1.BuckleyIPC.Subscribe.
func (c *buckleyIPCClient) Subscribe(ctx context.Context, req *connect.Request[proto.SubscribeRequest]) (*connect.ServerStreamForClient[proto.Event], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// SendCommand calls buckley.ipc.v1.BuckleyIPC.SendCommand.
func (c *buckleyIPCClient) SendCommand(ctx context.Context, req *connect.Request[proto.CommandRequest]) (*connect.Response[proto.CommandResponse], error) {
	return c.sendCommand.CallUnary(ctx, req)
}

// ListSessions calls buckley.ipc.v1.BuckleyIPC.ListSessions.
func (c *buckleyIPCClient) ListSessions(ctx context.Context, req *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls buckley.ipc.v1.BuckleyIPC.GetSession.
func (c *buckleyIPCClient) GetSession(ctx context.Context, req *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.SessionDetail], error) {
	return c.getSession.CallUnary(ctx, req)
}

// CreateHeadlessSession calls buckley.ipc.v1.BuckleyIPC.CreateHeadlessSession.
func (c *buckleyIPCClient) CreateHeadlessSession(ctx context.Context, req *connect.Request[proto.CreateHeadlessRequest]) (*connect.Response[proto.HeadlessSession], error) {
	return c.createHeadlessSession.CallUnary(ctx, req)
}

// DeleteHeadlessSession calls buckley.ipc.v1.BuckleyIPC.DeleteHeadlessSession.
func (c *buckleyIPCClient) DeleteHeadlessSession(ctx context.Context, req *connect.Request[proto.DeleteHeadlessRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteHeadlessSession.CallUnary(ctx, req)
}

// ListHeadlessSessions calls buckley.ipc.v1.BuckleyIPC.ListHeadlessSessions.
func (c *buckleyIPCClient) ListHeadlessSessions(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[proto.HeadlessSessionList], error) {
	return c.listHeadlessSessions.CallUnary(ctx, req)
}

// ListPlans calls buckley.ipc.v1.BuckleyIPC.ListPlans.
func (c *buckleyIPCClient) ListPlans(ctx context.Context, req *connect.Request[proto.ListPlansRequest]) (*connect.Response[proto.ListPlansResponse], error) {
	return c.listPlans.CallUnary(ctx, req)
}

// GetPlan calls buckley.ipc.v1.BuckleyIPC.GetPlan.
func (c *buckleyIPCClient) GetPlan(ctx context.Context, req *connect.Request[proto.GetPlanRequest]) (*connect.Response[proto.Plan], error) {
	return c.getPlan.CallUnary(ctx, req)
}

// ListProjects calls buckley.ipc.v1.BuckleyIPC.ListProjects.
func (c *buckleyIPCClient) ListProjects(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[proto.ProjectList], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// CreateProject calls buckley.ipc.v1.BuckleyIPC.CreateProject.
func (c *buckleyIPCClient) CreateProject(ctx context.Context, req *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.Project], error) {
	return c.createProject.CallUnary(ctx, req)
}

// ListPersonas calls buckley.ipc.v1.BuckleyIPC.ListPersonas.
func (c *buckleyIPCClient) ListPersonas(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[proto.PersonaList], error) {
	return c.listPersonas.CallUnary(ctx, req)
}

// WorkflowAction calls buckley.ipc.v1.BuckleyIPC.WorkflowAction.
func (c *buckleyIPCClient) WorkflowAction(ctx context.Context, req *connect.Request[proto.WorkflowActionRequest]) (*connect.Response[proto.WorkflowActionResponse], error) {
	return c.workflowAction.CallUnary(ctx, req)
}

// RegisterAgent calls buckley.ipc.v1.BuckleyIPC.RegisterAgent.
func (c *buckleyIPCClient) RegisterAgent(ctx context.Context, req *connect.Request[proto.RegisterAgentRequest]) (*connect.ServerStreamForClient[proto.AgentCommand], error) {
	return c.registerAgent.CallServerStream(ctx, req)
}

// ReportAgentResult calls buckley.ipc.v1.BuckleyIPC.ReportAgentResult.
func (c *buckleyIPCClient) ReportAgentResult(ctx context.Context, req *connect.Request[proto.AgentResult]) (*connect.Response[emptypb.Empty], error) {
	return c.reportAgentResult.CallUnary(ctx, req)
}

// AgentHeartbeat calls buckley.ipc.v1.BuckleyIPC.AgentHeartbeat.
func (c *buckleyIPCClient) AgentHeartbeat(ctx context.Context, req *connect.Request[proto.AgentHeartbeatRequest]) (*connect.Response[proto.AgentHeartbeatResponse], error) {
	return c.agentHeartbeat.CallUnary(ctx, req)
}

// ListAgents calls buckley.ipc.v1.BuckleyIPC.ListAgents.
func (c *buckleyIPCClient) ListAgents(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[proto.AgentList], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// ListPendingApprovals calls buckley.ipc.v1.BuckleyIPC.ListPendingApprovals.
func (c *buckleyIPCClient) ListPendingApprovals(ctx context.Context, req *connect.Request[proto.ListPendingApprovalsRequest]) (*connect.Response[proto.PendingApprovalsList], error) {
	return c.listPendingApprovals.CallUnary(ctx, req)
}

// ApproveToolCall calls buckley.ipc.v1.BuckleyIPC.ApproveToolCall.
func (c *buckleyIPCClient) ApproveToolCall(ctx context.Context, req *connect.Request[proto.ApproveToolCallRequest]) (*connect.Response[proto.ApproveToolCallResponse], error) {
	return c.approveToolCall.CallUnary(ctx, req)
}

// RejectToolCall calls buckley.ipc.v1.BuckleyIPC.RejectToolCall.
func (c *buckleyIPCClient) RejectToolCall(ctx context.Context, req *connect.Request[proto.RejectToolCallRequest]) (*connect.Response[proto.RejectToolCallResponse], error) {
	return c.rejectToolCall.CallUnary(ctx, req)
}

// GetApprovalPolicy calls buckley.ipc.v1.BuckleyIPC.GetApprovalPolicy.
func (c *buckleyIPCClient) GetApprovalPolicy(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[proto.ApprovalPolicy], error) {
	return c.getApprovalPolicy.CallUnary(ctx, req)
}

// UpdateApprovalPolicy calls buckley.ipc.v1.BuckleyIPC.UpdateApprovalPolicy.
func (c *buckleyIPCClient) UpdateApprovalPolicy(ctx context.Context, req *connect.Request[proto.UpdateApprovalPolicyRequest]) (*connect.Response[proto.ApprovalPolicy], error) {
	return c.updateApprovalPolicy.CallUnary(ctx, req)
}

// GetAuditLog calls buckley.ipc.v1.BuckleyIPC.GetAuditLog.
func (c *buckleyIPCClient) GetAuditLog(ctx context.Context, req *connect.Request[proto.GetAuditLogRequest]) (*connect.Response[proto.AuditLogResponse], error) {
	return c.getAuditLog.CallUnary(ctx, req)
}

// SubscribePush calls buckley.ipc.v1.BuckleyIPC.SubscribePush.
func (c *buckleyIPCClient) SubscribePush(ctx context.Context, req *connect.Request[proto.PushSubscriptionRequest]) (*connect.Response[proto.PushSubscriptionResponse], error) {
	return c.subscribePush.CallUnary(ctx, req)
}

// UnsubscribePush calls buckley.ipc.v1.BuckleyIPC.UnsubscribePush.
func (c *buckleyIPCClient) UnsubscribePush(ctx context.Context, req *connect.Request[proto.UnsubscribePushRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.unsubscribePush.CallUnary(ctx, req)
}

// GetVAPIDPublicKey calls buckley.ipc.v1.BuckleyIPC.GetVAPIDPublicKey.
func (c *buckleyIPCClient) GetVAPIDPublicKey(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[proto.VAPIDPublicKeyResponse], error) {
	return c.getVAPIDPublicKey.CallUnary(ctx, req)
}

// BuckleyIPCHandler is an implementation of the buckley.ipc.v1.BuckleyIPC service.
type BuckleyIPCHandler interface {
	// Subscribe opens a server-streaming connection for real-time events.
	// Used by web UI, CLI watchers, and monitoring tools.
	Subscribe(context.Context, *connect.Request[proto.SubscribeRequest], *connect.ServerStream[proto.Event]) error
	// SendCommand dispatches user input or slash commands to a session.
	SendCommand(context.Context, *connect.Request[proto.CommandRequest]) (*connect.Response[proto.CommandResponse], error)
	// ListSessions returns all active and recent sessions.
	ListSessions(context.Context, *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error)
	// GetSession returns detailed session state including messages and todos.
	GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.SessionDetail], error)
	// CreateHeadlessSession spawns an isolated session on the server.
	CreateHeadlessSession(context.Context, *connect.Request[proto.CreateHeadlessRequest]) (*connect.Response[proto.HeadlessSession], error)
	// DeleteHeadlessSession terminates and cleans up a headless session.
	DeleteHeadlessSession(context.Context, *connect.Request[proto.DeleteHeadlessRequest]) (*connect.Response[emptypb.Empty], error)
	// ListHeadlessSessions returns all running headless sessions.
	ListHeadlessSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.HeadlessSessionList], error)
	// ListPlans returns all available plans.
	ListPlans(context.Context, *connect.Request[proto.ListPlansRequest]) (*connect.Response[proto.ListPlansResponse], error)
	// GetPlan returns detailed plan information including tasks.
	GetPlan(context.Context, *connect.Request[proto.GetPlanRequest]) (*connect.Response[proto.Plan], error)
	// ListProjects returns all known projects.
	ListProjects(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.ProjectList], error)
	// CreateProject registers a new project.
	CreateProject(context.Context, *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.Project], error)
	// ListPersonas returns available AI personas.
	ListPersonas(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.PersonaList], error)
	// WorkflowAction triggers plan/execute/pause/resume operations.
	WorkflowAction(context.Context, *connect.Request[proto.WorkflowActionRequest]) (*connect.Response[proto.WorkflowActionResponse], error)
	// RegisterAgent connects a host agent to the server.
	// The agent receives commands via the returned stream.
	RegisterAgent(context.Context, *connect.Request[proto.RegisterAgentRequest], *connect.ServerStream[proto.AgentCommand]) error
	// ReportAgentResult sends execution results back to the server.
	ReportAgentResult(context.Context, *connect.Request[proto.AgentResult]) (*connect.Response[emptypb.Empty], error)
	// AgentHeartbeat keeps the agent connection alive and reports status.
	AgentHeartbeat(context.Context, *connect.Request[proto.AgentHeartbeatRequest]) (*connect.Response[proto.AgentHeartbeatResponse], error)
	// ListAgents returns all connected host agents.
	ListAgents(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.AgentList], error)
	// ListPendingApprovals returns pending tool call approvals for a session.
	ListPendingApprovals(context.Context, *connect.Request[proto.ListPendingApprovalsRequest]) (*connect.Response[proto.PendingApprovalsList], error)
	// ApproveToolCall approves a pending tool call.
	ApproveToolCall(context.Context, *connect.Request[proto.ApproveToolCallRequest]) (*connect.Response[proto.ApproveToolCallResponse], error)
	// RejectToolCall rejects a pending tool call.
	RejectToolCall(context.Context, *connect.Request[proto.RejectToolCallRequest]) (*connect.Response[proto.RejectToolCallResponse], error)
	// GetApprovalPolicy returns the active approval policy.
	GetApprovalPolicy(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.ApprovalPolicy], error)
	// UpdateApprovalPolicy updates the approval policy configuration.
	UpdateApprovalPolicy(context.Context, *connect.Request[proto.UpdateApprovalPolicyRequest]) (*connect.Response[proto.ApprovalPolicy], error)
	// GetAuditLog returns the tool execution audit log for a session.
	GetAuditLog(context.Context, *connect.Request[proto.GetAuditLogRequest]) (*connect.Response[proto.AuditLogResponse], error)
	// SubscribePush registers a browser for push notifications.
	SubscribePush(context.Context, *connect.Request[proto.PushSubscriptionRequest]) (*connect.Response[proto.PushSubscriptionResponse], error)
	// UnsubscribePush removes a push subscription.
	UnsubscribePush(context.Context, *connect.Request[proto.UnsubscribePushRequest]) (*connect.Response[emptypb.Empty], error)
	// GetVAPIDPublicKey returns the server's VAPID public key for Web Push.
	GetVAPIDPublicKey(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.VAPIDPublicKeyResponse], error)
}

// NewBuckleyIPCHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBuckleyIPCHandler(svc BuckleyIPCHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	buckleyIPCMethods := proto.File_ipc_proto.Services().ByName("BuckleyIPC").Methods()
	buckleyIPCSubscribeHandler := connect.NewServerStreamHandler(
		BuckleyIPCSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(buckleyIPCMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCSendCommandHandler := connect.NewUnaryHandler(
		BuckleyIPCSendCommandProcedure,
		svc.SendCommand,
		connect.WithSchema(buckleyIPCMethods.ByName("SendCommand")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListSessionsHandler := connect.NewUnaryHandler(
		BuckleyIPCListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(buckleyIPCMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCGetSessionHandler := connect.NewUnaryHandler(
		BuckleyIPCGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(buckleyIPCMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCCreateHeadlessSessionHandler := connect.NewUnaryHandler(
		BuckleyIPCCreateHeadlessSessionProcedure,
		svc.CreateHeadlessSession,
		connect.WithSchema(buckleyIPCMethods.ByName("CreateHeadlessSession")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCDeleteHeadlessSessionHandler := connect.NewUnaryHandler(
		BuckleyIPCDeleteHeadlessSessionProcedure,
		svc.DeleteHeadlessSession,
		connect.WithSchema(buckleyIPCMethods.ByName("DeleteHeadlessSession")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListHeadlessSessionsHandler := connect.NewUnaryHandler(
		BuckleyIPCListHeadlessSessionsProcedure,
		svc.ListHeadlessSessions,
		connect.WithSchema(buckleyIPCMethods.ByName("ListHeadlessSessions")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListPlansHandler := connect.NewUnaryHandler(
		BuckleyIPCListPlansProcedure,
		svc.ListPlans,
		connect.WithSchema(buckleyIPCMethods.ByName("ListPlans")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCGetPlanHandler := connect.NewUnaryHandler(
		BuckleyIPCGetPlanProcedure,
		svc.GetPlan,
		connect.WithSchema(buckleyIPCMethods.ByName("GetPlan")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListProjectsHandler := connect.NewUnaryHandler(
		BuckleyIPCListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(buckleyIPCMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCCreateProjectHandler := connect.NewUnaryHandler(
		BuckleyIPCCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(buckleyIPCMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListPersonasHandler := connect.NewUnaryHandler(
		BuckleyIPCListPersonasProcedure,
		svc.ListPersonas,
		connect.WithSchema(buckleyIPCMethods.ByName("ListPersonas")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCWorkflowActionHandler := connect.NewUnaryHandler(
		BuckleyIPCWorkflowActionProcedure,
		svc.WorkflowAction,
		connect.WithSchema(buckleyIPCMethods.ByName("WorkflowAction")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCRegisterAgentHandler := connect.NewServerStreamHandler(
		BuckleyIPCRegisterAgentProcedure,
		svc.RegisterAgent,
		connect.WithSchema(buckleyIPCMethods.ByName("RegisterAgent")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCReportAgentResultHandler := connect.NewUnaryHandler(
		BuckleyIPCReportAgentResultProcedure,
		svc.ReportAgentResult,
		connect.WithSchema(buckleyIPCMethods.ByName("ReportAgentResult")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCAgentHeartbeatHandler := connect.NewUnaryHandler(
		BuckleyIPCAgentHeartbeatProcedure,
		svc.AgentHeartbeat,
		connect.WithSchema(buckleyIPCMethods.ByName("AgentHeartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListAgentsHandler := connect.NewUnaryHandler(
		BuckleyIPCListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(buckleyIPCMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCListPendingApprovalsHandler := connect.NewUnaryHandler(
		BuckleyIPCListPendingApprovalsProcedure,
		svc.ListPendingApprovals,
		connect.WithSchema(buckleyIPCMethods.ByName("ListPendingApprovals")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCApproveToolCallHandler := connect.NewUnaryHandler(
		BuckleyIPCApproveToolCallProcedure,
		svc.ApproveToolCall,
		connect.WithSchema(buckleyIPCMethods.ByName("ApproveToolCall")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCRejectToolCallHandler := connect.NewUnaryHandler(
		BuckleyIPCRejectToolCallProcedure,
		svc.RejectToolCall,
		connect.WithSchema(buckleyIPCMethods.ByName("RejectToolCall")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCGetApprovalPolicyHandler := connect.NewUnaryHandler(
		BuckleyIPCGetApprovalPolicyProcedure,
		svc.GetApprovalPolicy,
		connect.WithSchema(buckleyIPCMethods.ByName("GetApprovalPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCUpdateApprovalPolicyHandler := connect.NewUnaryHandler(
		BuckleyIPCUpdateApprovalPolicyProcedure,
		svc.UpdateApprovalPolicy,
		connect.WithSchema(buckleyIPCMethods.ByName("UpdateApprovalPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCGetAuditLogHandler := connect.NewUnaryHandler(
		BuckleyIPCGetAuditLogProcedure,
		svc.GetAuditLog,
		connect.WithSchema(buckleyIPCMethods.ByName("GetAuditLog")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCSubscribePushHandler := connect.NewUnaryHandler(
		BuckleyIPCSubscribePushProcedure,
		svc.SubscribePush,
		connect.WithSchema(buckleyIPCMethods.ByName("SubscribePush")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCUnsubscribePushHandler := connect.NewUnaryHandler(
		BuckleyIPCUnsubscribePushProcedure,
		svc.UnsubscribePush,
		connect.WithSchema(buckleyIPCMethods.ByName("UnsubscribePush")),
		connect.WithHandlerOptions(opts...),
	)
	buckleyIPCGetVAPIDPublicKeyHandler := connect.NewUnaryHandler(
		BuckleyIPCGetVAPIDPublicKeyProcedure,
		svc.GetVAPIDPublicKey,
		connect.WithSchema(buckleyIPCMethods.ByName("GetVAPIDPublicKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/buckley.ipc.v1.BuckleyIPC/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BuckleyIPCSubscribeProcedure:
			buckleyIPCSubscribeHandler.ServeHTTP(w, r)
		case BuckleyIPCSendCommandProcedure:
			buckleyIPCSendCommandHandler.ServeHTTP(w, r)
		case BuckleyIPCListSessionsProcedure:
			buckleyIPCListSessionsHandler.ServeHTTP(w, r)
		case BuckleyIPCGetSessionProcedure:
			buckleyIPCGetSessionHandler.ServeHTTP(w, r)
		case BuckleyIPCCreateHeadlessSessionProcedure:
			buckleyIPCCreateHeadlessSessionHandler.ServeHTTP(w, r)
		case BuckleyIPCDeleteHeadlessSessionProcedure:
			buckleyIPCDeleteHeadlessSessionHandler.ServeHTTP(w, r)
		case BuckleyIPCListHeadlessSessionsProcedure:
			buckleyIPCListHeadlessSessionsHandler.ServeHTTP(w, r)
		case BuckleyIPCListPlansProcedure:
			buckleyIPCListPlansHandler.ServeHTTP(w, r)
		case BuckleyIPCGetPlanProcedure:
			buckleyIPCGetPlanHandler.ServeHTTP(w, r)
		case BuckleyIPCListProjectsProcedure:
			buckleyIPCListProjectsHandler.ServeHTTP(w, r)
		case BuckleyIPCCreateProjectProcedure:
			buckleyIPCCreateProjectHandler.ServeHTTP(w, r)
		case BuckleyIPCListPersonasProcedure:
			buckleyIPCListPersonasHandler.ServeHTTP(w, r)
		case BuckleyIPCWorkflowActionProcedure:
			buckleyIPCWorkflowActionHandler.ServeHTTP(w, r)
		case BuckleyIPCRegisterAgentProcedure:
			buckleyIPCRegisterAgentHandler.ServeHTTP(w, r)
		case BuckleyIPCReportAgentResultProcedure:
			buckleyIPCReportAgentResultHandler.ServeHTTP(w, r)
		case BuckleyIPCAgentHeartbeatProcedure:
			buckleyIPCAgentHeartbeatHandler.ServeHTTP(w, r)
		case BuckleyIPCListAgentsProcedure:
			buckleyIPCListAgentsHandler.ServeHTTP(w, r)
		case BuckleyIPCListPendingApprovalsProcedure:
			buckleyIPCListPendingApprovalsHandler.ServeHTTP(w, r)
		case BuckleyIPCApproveToolCallProcedure:
			buckleyIPCApproveToolCallHandler.ServeHTTP(w, r)
		case BuckleyIPCRejectToolCallProcedure:
			buckleyIPCRejectToolCallHandler.ServeHTTP(w, r)
		case BuckleyIPCGetApprovalPolicyProcedure:
			buckleyIPCGetApprovalPolicyHandler.ServeHTTP(w, r)
		case BuckleyIPCUpdateApprovalPolicyProcedure:
			buckleyIPCUpdateApprovalPolicyHandler.ServeHTTP(w, r)
		case BuckleyIPCGetAuditLogProcedure:
			buckleyIPCGetAuditLogHandler.ServeHTTP(w, r)
		case BuckleyIPCSubscribePushProcedure:
			buckleyIPCSubscribePushHandler.ServeHTTP(w, r)
		case BuckleyIPCUnsubscribePushProcedure:
			buckleyIPCUnsubscribePushHandler.ServeHTTP(w, r)
		case BuckleyIPCGetVAPIDPublicKeyProcedure:
			buckleyIPCGetVAPIDPublicKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBuckleyIPCHandler returns CodeUnimplemented from all methods.
type UnimplementedBuckleyIPCHandler struct{}

func (UnimplementedBuckleyIPCHandler) Subscribe(context.Context, *connect.Request[proto.SubscribeRequest], *connect.ServerStream[proto.Event]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.Subscribe is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) SendCommand(context.Context, *connect.Request[proto.CommandRequest]) (*connect.Response[proto.CommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.SendCommand is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListSessions(context.Context, *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListSessions is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.SessionDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.GetSession is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) CreateHeadlessSession(context.Context, *connect.Request[proto.CreateHeadlessRequest]) (*connect.Response[proto.HeadlessSession], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.CreateHeadlessSession is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) DeleteHeadlessSession(context.Context, *connect.Request[proto.DeleteHeadlessRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.DeleteHeadlessSession is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListHeadlessSessions(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.HeadlessSessionList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListHeadlessSessions is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListPlans(context.Context, *connect.Request[proto.ListPlansRequest]) (*connect.Response[proto.ListPlansResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListPlans is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) GetPlan(context.Context, *connect.Request[proto.GetPlanRequest]) (*connect.Response[proto.Plan], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.GetPlan is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListProjects(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.ProjectList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListProjects is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) CreateProject(context.Context, *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.Project], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.CreateProject is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListPersonas(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.PersonaList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListPersonas is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) WorkflowAction(context.Context, *connect.Request[proto.WorkflowActionRequest]) (*connect.Response[proto.WorkflowActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.WorkflowAction is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) RegisterAgent(context.Context, *connect.Request[proto.RegisterAgentRequest], *connect.ServerStream[proto.AgentCommand]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.RegisterAgent is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ReportAgentResult(context.Context, *connect.Request[proto.AgentResult]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ReportAgentResult is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) AgentHeartbeat(context.Context, *connect.Request[proto.AgentHeartbeatRequest]) (*connect.Response[proto.AgentHeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.AgentHeartbeat is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListAgents(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.AgentList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListAgents is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ListPendingApprovals(context.Context, *connect.Request[proto.ListPendingApprovalsRequest]) (*connect.Response[proto.PendingApprovalsList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ListPendingApprovals is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) ApproveToolCall(context.Context, *connect.Request[proto.ApproveToolCallRequest]) (*connect.Response[proto.ApproveToolCallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.ApproveToolCall is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) RejectToolCall(context.Context, *connect.Request[proto.RejectToolCallRequest]) (*connect.Response[proto.RejectToolCallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.RejectToolCall is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) GetApprovalPolicy(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.ApprovalPolicy], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.GetApprovalPolicy is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) UpdateApprovalPolicy(context.Context, *connect.Request[proto.UpdateApprovalPolicyRequest]) (*connect.Response[proto.ApprovalPolicy], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.UpdateApprovalPolicy is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) GetAuditLog(context.Context, *connect.Request[proto.GetAuditLogRequest]) (*connect.Response[proto.AuditLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.GetAuditLog is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) SubscribePush(context.Context, *connect.Request[proto.PushSubscriptionRequest]) (*connect.Response[proto.PushSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.SubscribePush is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) UnsubscribePush(context.Context, *connect.Request[proto.UnsubscribePushRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.UnsubscribePush is not implemented"))
}

func (UnimplementedBuckleyIPCHandler) GetVAPIDPublicKey(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[proto.VAPIDPublicKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buckley.ipc.v1.BuckleyIPC.GetVAPIDPublicKey is not implemented"))
}
