package containers

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SecretsManager handles env file generation and secret syncing
type SecretsManager struct {
	workDir string
}

// NewSecretsManager creates a new secrets manager
func NewSecretsManager(workDir string) *SecretsManager {
	return &SecretsManager{workDir: workDir}
}

// GenerateEnvFile loads host .env, scrubs sensitive keys, and writes to .env.container
func (sm *SecretsManager) GenerateEnvFile() error {
	hostEnv := sm.loadHostEnv()
	containerEnv := sm.filterSecrets(hostEnv)
	return sm.writeEnvFile(".env.container", containerEnv)
}

// ValidateSecrets checks if required secrets are present
func (sm *SecretsManager) ValidateSecrets(required []string) []string {
	missing := []string{}
	for _, key := range required {
		if os.Getenv(key) == "" {
			missing = append(missing, key)
		}
	}
	return missing
}

// loadHostEnv loads environment variables from .env file and current environment
func (sm *SecretsManager) loadHostEnv() map[string]string {
	env := make(map[string]string)

	// Load from .env file if it exists
	envPath := filepath.Join(sm.workDir, ".env")
	if file, err := os.Open(envPath); err == nil {
		defer file.Close()

		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())

			// Skip comments and empty lines
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}

			// Parse KEY=VALUE
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				key := strings.TrimSpace(parts[0])
				value := strings.TrimSpace(parts[1])

				// Remove quotes if present
				value = strings.Trim(value, "\"'")

				env[key] = value
			}
		}
	}

	// Also include current environment variables
	for _, e := range os.Environ() {
		parts := strings.SplitN(e, "=", 2)
		if len(parts) == 2 {
			key := parts[0]
			value := parts[1]

			// Only add if not already in env (file takes precedence)
			if _, exists := env[key]; !exists {
				env[key] = value
			}
		}
	}

	return env
}

// filterSecrets removes sensitive keys from the environment
func (sm *SecretsManager) filterSecrets(env map[string]string) map[string]string {
	// List of sensitive key patterns to exclude
	sensitivePatterns := []string{
		"PASSWORD",
		"SECRET",
		"TOKEN",
		"API_KEY",
		"PRIVATE_KEY",
		"APIKEY",
		"AUTH",
	}

	// List of safe key patterns to always include
	safePatterns := []string{
		"PATH",
		"HOME",
		"USER",
		"SHELL",
		"LANG",
		"TERM",
	}

	filtered := make(map[string]string)

	for key, value := range env {
		upperKey := strings.ToUpper(key)

		// Check if key is in safe list
		isSafe := false
		for _, pattern := range safePatterns {
			if strings.Contains(upperKey, pattern) {
				isSafe = true
				break
			}
		}

		if isSafe {
			filtered[key] = value
			continue
		}

		// Check if key contains sensitive patterns
		isSensitive := false
		for _, pattern := range sensitivePatterns {
			if strings.Contains(upperKey, pattern) {
				isSensitive = true
				break
			}
		}

		// Only include if not sensitive
		if !isSensitive {
			filtered[key] = value
		}
	}

	return filtered
}

// writeEnvFile writes environment variables to a file
func (sm *SecretsManager) writeEnvFile(filename string, env map[string]string) error {
	path := filepath.Join(sm.workDir, filename)

	// Use restrictive permissions (0600) since env files may contain sensitive values
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("failed to create env file: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)

	// Write header comment
	writer.WriteString("# Container environment file\n")
	writer.WriteString("# Generated by Buckley - sensitive keys filtered out\n\n")

	// Write each environment variable
	for key, value := range env {
		// Quote values that contain spaces
		if strings.Contains(value, " ") {
			value = fmt.Sprintf(`"%s"`, value)
		}

		line := fmt.Sprintf("%s=%s\n", key, value)
		writer.WriteString(line)
	}

	return writer.Flush()
}

// GetRequiredSecrets returns a list of secrets required for the services
func (sm *SecretsManager) GetRequiredSecrets(services []string) []string {
	required := []string{}

	for _, svc := range services {
		switch svc {
		case "postgres":
			required = append(required, "POSTGRES_PASSWORD")
		case "mysql":
			required = append(required, "MYSQL_ROOT_PASSWORD")
		case "mongodb":
			required = append(required, "MONGO_INITDB_ROOT_PASSWORD")
		case "redis":
			// Redis doesn't require secrets by default
		}
	}

	return required
}
