// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/orchestrator (interfaces: ModelClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/odvcencio/buckley/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockModelClient is a mock of ModelClient interface.
type MockModelClient struct {
	ctrl     *gomock.Controller
	recorder *MockModelClientMockRecorder
}

// MockModelClientMockRecorder is the mock recorder for MockModelClient.
type MockModelClientMockRecorder struct {
	mock *MockModelClient
}

// NewMockModelClient creates a new mock instance.
func NewMockModelClient(ctrl *gomock.Controller) *MockModelClient {
	mock := &MockModelClient{ctrl: ctrl}
	mock.recorder = &MockModelClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelClient) EXPECT() *MockModelClientMockRecorder {
	return m.recorder
}

// ChatCompletion mocks base method.
func (m *MockModelClient) ChatCompletion(arg0 context.Context, arg1 model.ChatRequest) (*model.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletion", arg0, arg1)
	ret0, _ := ret[0].(*model.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatCompletion indicates an expected call of ChatCompletion.
func (mr *MockModelClientMockRecorder) ChatCompletion(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletion", reflect.TypeOf((*MockModelClient)(nil).ChatCompletion), arg0, arg1)
}

// SupportsReasoning mocks base method.
func (m *MockModelClient) SupportsReasoning(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsReasoning", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsReasoning indicates an expected call of SupportsReasoning.
func (mr *MockModelClientMockRecorder) SupportsReasoning(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsReasoning", reflect.TypeOf((*MockModelClient)(nil).SupportsReasoning), arg0)
}
