// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/tool/builtin (interfaces: TodoStore)
//
// Generated by this command:
//
//	mockgen -package=builtin -destination=mock_todo_store_test.go github.com/odvcencio/buckley/pkg/tool/builtin TodoStore
//

// Package builtin is a generated GoMock package.
package builtin

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTodoStore is a mock of TodoStore interface.
type MockTodoStore struct {
	ctrl     *gomock.Controller
	recorder *MockTodoStoreMockRecorder
	isgomock struct{}
}

// MockTodoStoreMockRecorder is the mock recorder for MockTodoStore.
type MockTodoStoreMockRecorder struct {
	mock *MockTodoStore
}

// NewMockTodoStore creates a new mock instance.
func NewMockTodoStore(ctrl *gomock.Controller) *MockTodoStore {
	mock := &MockTodoStore{ctrl: ctrl}
	mock.recorder = &MockTodoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoStore) EXPECT() *MockTodoStoreMockRecorder {
	return m.recorder
}

// CreateCheckpoint mocks base method.
func (m *MockTodoStore) CreateCheckpoint(checkpoint *TodoCheckpointData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckpoint", checkpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCheckpoint indicates an expected call of CreateCheckpoint.
func (mr *MockTodoStoreMockRecorder) CreateCheckpoint(checkpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckpoint", reflect.TypeOf((*MockTodoStore)(nil).CreateCheckpoint), checkpoint)
}

// CreateTodo mocks base method.
func (m *MockTodoStore) CreateTodo(todo *TodoItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoStoreMockRecorder) CreateTodo(todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoStore)(nil).CreateTodo), todo)
}

// DeleteTodos mocks base method.
func (m *MockTodoStore) DeleteTodos(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodos", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodos indicates an expected call of DeleteTodos.
func (mr *MockTodoStoreMockRecorder) DeleteTodos(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodos", reflect.TypeOf((*MockTodoStore)(nil).DeleteTodos), sessionID)
}

// EnsureSession mocks base method.
func (m *MockTodoStore) EnsureSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureSession indicates an expected call of EnsureSession.
func (mr *MockTodoStoreMockRecorder) EnsureSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSession", reflect.TypeOf((*MockTodoStore)(nil).EnsureSession), sessionID)
}

// GetActiveTodo mocks base method.
func (m *MockTodoStore) GetActiveTodo(sessionID string) (*TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTodo", sessionID)
	ret0, _ := ret[0].(*TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTodo indicates an expected call of GetActiveTodo.
func (mr *MockTodoStoreMockRecorder) GetActiveTodo(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTodo", reflect.TypeOf((*MockTodoStore)(nil).GetActiveTodo), sessionID)
}

// GetLatestCheckpoint mocks base method.
func (m *MockTodoStore) GetLatestCheckpoint(sessionID string) (*TodoCheckpointData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestCheckpoint", sessionID)
	ret0, _ := ret[0].(*TodoCheckpointData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestCheckpoint indicates an expected call of GetLatestCheckpoint.
func (mr *MockTodoStoreMockRecorder) GetLatestCheckpoint(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestCheckpoint", reflect.TypeOf((*MockTodoStore)(nil).GetLatestCheckpoint), sessionID)
}

// GetTodos mocks base method.
func (m *MockTodoStore) GetTodos(sessionID string) ([]TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodos", sessionID)
	ret0, _ := ret[0].([]TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodos indicates an expected call of GetTodos.
func (mr *MockTodoStoreMockRecorder) GetTodos(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodos", reflect.TypeOf((*MockTodoStore)(nil).GetTodos), sessionID)
}

// UpdateTodoStatus mocks base method.
func (m *MockTodoStore) UpdateTodoStatus(id int64, status, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodoStatus", id, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTodoStatus indicates an expected call of UpdateTodoStatus.
func (mr *MockTodoStoreMockRecorder) UpdateTodoStatus(id, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodoStatus", reflect.TypeOf((*MockTodoStore)(nil).UpdateTodoStatus), id, status, errorMessage)
}
