// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/ipc/command (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -package=command -destination=mock_handler_test.go github.com/odvcencio/buckley/pkg/ipc/command Handler
//

// Package command is a generated GoMock package.
package command

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleSessionCommand mocks base method.
func (m *MockHandler) HandleSessionCommand(arg0 SessionCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSessionCommand", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSessionCommand indicates an expected call of HandleSessionCommand.
func (mr *MockHandlerMockRecorder) HandleSessionCommand(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSessionCommand", reflect.TypeOf((*MockHandler)(nil).HandleSessionCommand), arg0)
}
