// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/storage (interfaces: Observer)
//
// Generated by this command:
//
//	mockgen -package=storage -destination=mock_observer_test.go github.com/odvcencio/buckley/pkg/storage Observer
//

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// HandleStorageEvent mocks base method.
func (m *MockObserver) HandleStorageEvent(arg0 Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleStorageEvent", arg0)
}

// HandleStorageEvent indicates an expected call of HandleStorageEvent.
func (mr *MockObserverMockRecorder) HandleStorageEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStorageEvent", reflect.TypeOf((*MockObserver)(nil).HandleStorageEvent), arg0)
}
