// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/artifact (interfaces: TokenCounter)
//
// Generated by this command:
//
//	mockgen -package=artifact -destination=mock_token_counter_test.go github.com/odvcencio/buckley/pkg/artifact TokenCounter
//

// Package artifact is a generated GoMock package.
package artifact

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenCounter is a mock of TokenCounter interface.
type MockTokenCounter struct {
	ctrl     *gomock.Controller
	recorder *MockTokenCounterMockRecorder
	isgomock struct{}
}

// MockTokenCounterMockRecorder is the mock recorder for MockTokenCounter.
type MockTokenCounterMockRecorder struct {
	mock *MockTokenCounter
}

// NewMockTokenCounter creates a new mock instance.
func NewMockTokenCounter(ctrl *gomock.Controller) *MockTokenCounter {
	mock := &MockTokenCounter{ctrl: ctrl}
	mock.recorder = &MockTokenCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenCounter) EXPECT() *MockTokenCounterMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockTokenCounter) Count(text string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", text)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTokenCounterMockRecorder) Count(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTokenCounter)(nil).Count), text)
}
