// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/artifact (interfaces: ModelClient)
//
// Generated by this command:
//
//	mockgen -package=artifact -destination=mock_model_client_test.go github.com/odvcencio/buckley/pkg/artifact ModelClient
//

// Package artifact is a generated GoMock package.
package artifact

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockModelClient is a mock of ModelClient interface.
type MockModelClient struct {
	ctrl     *gomock.Controller
	recorder *MockModelClientMockRecorder
	isgomock struct{}
}

// MockModelClientMockRecorder is the mock recorder for MockModelClient.
type MockModelClientMockRecorder struct {
	mock *MockModelClient
}

// NewMockModelClient creates a new mock instance.
func NewMockModelClient(ctrl *gomock.Controller) *MockModelClient {
	mock := &MockModelClient{ctrl: ctrl}
	mock.recorder = &MockModelClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelClient) EXPECT() *MockModelClientMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockModelClient) Complete(ctx context.Context, model, prompt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, model, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockModelClientMockRecorder) Complete(ctx, model, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockModelClient)(nil).Complete), ctx, model, prompt)
}
