// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/model (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package=model -destination=mock_provider_test.go github.com/odvcencio/buckley/pkg/model Provider
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// ChatCompletion mocks base method.
func (m *MockProvider) ChatCompletion(ctx context.Context, req ChatRequest) (*ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletion", ctx, req)
	ret0, _ := ret[0].(*ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatCompletion indicates an expected call of ChatCompletion.
func (mr *MockProviderMockRecorder) ChatCompletion(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletion", reflect.TypeOf((*MockProvider)(nil).ChatCompletion), ctx, req)
}

// ChatCompletionStream mocks base method.
func (m *MockProvider) ChatCompletionStream(ctx context.Context, req ChatRequest) (<-chan StreamChunk, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletionStream", ctx, req)
	ret0, _ := ret[0].(<-chan StreamChunk)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// ChatCompletionStream indicates an expected call of ChatCompletionStream.
func (mr *MockProviderMockRecorder) ChatCompletionStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletionStream", reflect.TypeOf((*MockProvider)(nil).ChatCompletionStream), ctx, req)
}

// FetchCatalog mocks base method.
func (m *MockProvider) FetchCatalog() (*ModelCatalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCatalog")
	ret0, _ := ret[0].(*ModelCatalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCatalog indicates an expected call of FetchCatalog.
func (mr *MockProviderMockRecorder) FetchCatalog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCatalog", reflect.TypeOf((*MockProvider)(nil).FetchCatalog))
}

// GetModelInfo mocks base method.
func (m *MockProvider) GetModelInfo(modelID string) (*ModelInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelInfo", modelID)
	ret0, _ := ret[0].(*ModelInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelInfo indicates an expected call of GetModelInfo.
func (mr *MockProviderMockRecorder) GetModelInfo(modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelInfo", reflect.TypeOf((*MockProvider)(nil).GetModelInfo), modelID)
}

// ID mocks base method.
func (m *MockProvider) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockProviderMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockProvider)(nil).ID))
}
