// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/orchestrator (interfaces: PlanStore)
//
// Generated by this command:
//
//	mockgen -package=orchestrator -destination=mock_plan_store_test.go github.com/odvcencio/buckley/pkg/orchestrator PlanStore
//

// Package orchestrator is a generated GoMock package.
package orchestrator

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlanStore is a mock of PlanStore interface.
type MockPlanStore struct {
	ctrl     *gomock.Controller
	recorder *MockPlanStoreMockRecorder
	isgomock struct{}
}

// MockPlanStoreMockRecorder is the mock recorder for MockPlanStore.
type MockPlanStoreMockRecorder struct {
	mock *MockPlanStore
}

// NewMockPlanStore creates a new mock instance.
func NewMockPlanStore(ctrl *gomock.Controller) *MockPlanStore {
	mock := &MockPlanStore{ctrl: ctrl}
	mock.recorder = &MockPlanStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanStore) EXPECT() *MockPlanStoreMockRecorder {
	return m.recorder
}

// ListPlans mocks base method.
func (m *MockPlanStore) ListPlans() ([]Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans")
	ret0, _ := ret[0].([]Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlans indicates an expected call of ListPlans.
func (mr *MockPlanStoreMockRecorder) ListPlans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockPlanStore)(nil).ListPlans))
}

// LoadPlan mocks base method.
func (m *MockPlanStore) LoadPlan(planID string) (*Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPlan", planID)
	ret0, _ := ret[0].(*Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPlan indicates an expected call of LoadPlan.
func (mr *MockPlanStoreMockRecorder) LoadPlan(planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPlan", reflect.TypeOf((*MockPlanStore)(nil).LoadPlan), planID)
}

// ReadLog mocks base method.
func (m *MockPlanStore) ReadLog(planID, logKind string, limit int) ([]string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLog", planID, logKind, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadLog indicates an expected call of ReadLog.
func (mr *MockPlanStoreMockRecorder) ReadLog(planID, logKind, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLog", reflect.TypeOf((*MockPlanStore)(nil).ReadLog), planID, logKind, limit)
}

// SavePlan mocks base method.
func (m *MockPlanStore) SavePlan(plan *Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePlan", plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePlan indicates an expected call of SavePlan.
func (mr *MockPlanStoreMockRecorder) SavePlan(plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePlan", reflect.TypeOf((*MockPlanStore)(nil).SavePlan), plan)
}
