// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/orchestrator (interfaces: SkillRegistry,SkillConversation,PhaseSkill)
//
// Generated by this command:
//
//	mockgen -package=orchestrator -destination=pkg/orchestrator/skill_manager_mocks_test.go github.com/odvcencio/buckley/pkg/orchestrator SkillRegistry,SkillConversation,PhaseSkill
//

// Package orchestrator is a generated GoMock package.
package orchestrator

import (
	reflect "reflect"

	"github.com/odvcencio/buckley/pkg/skill"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillRegistry is a mock of SkillRegistry interface.
type MockSkillRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSkillRegistryMockRecorder
	isgomock struct{}
}

// MockSkillRegistryMockRecorder is the mock recorder for MockSkillRegistry.
type MockSkillRegistryMockRecorder struct {
	mock *MockSkillRegistry
}

// NewMockSkillRegistry creates a new mock instance.
func NewMockSkillRegistry(ctrl *gomock.Controller) *MockSkillRegistry {
	mock := &MockSkillRegistry{ctrl: ctrl}
	mock.recorder = &MockSkillRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillRegistry) EXPECT() *MockSkillRegistryMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockSkillRegistry) Activate(name, scope, activatedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", name, scope, activatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockSkillRegistryMockRecorder) Activate(name, scope, activatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockSkillRegistry)(nil).Activate), name, scope, activatedBy)
}

// Deactivate mocks base method.
func (m *MockSkillRegistry) Deactivate(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockSkillRegistryMockRecorder) Deactivate(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockSkillRegistry)(nil).Deactivate), name)
}

// Get mocks base method.
func (m *MockSkillRegistry) Get(name string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSkillRegistryMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSkillRegistry)(nil).Get), name)
}

// GetByPhase mocks base method.
func (m *MockSkillRegistry) GetByPhase(phase string) []skill.PhaseSkill {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhase", phase)
	ret0, _ := ret[0].([]skill.PhaseSkill)
	return ret0
}

// GetByPhase indicates an expected call of GetByPhase.
func (mr *MockSkillRegistryMockRecorder) GetByPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhase", reflect.TypeOf((*MockSkillRegistry)(nil).GetByPhase), phase)
}

// GetDescriptions mocks base method.
func (m *MockSkillRegistry) GetDescriptions() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescriptions")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescriptions indicates an expected call of GetDescriptions.
func (mr *MockSkillRegistryMockRecorder) GetDescriptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescriptions", reflect.TypeOf((*MockSkillRegistry)(nil).GetDescriptions))
}

// IsActive mocks base method.
func (m *MockSkillRegistry) IsActive(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsActive indicates an expected call of IsActive.
func (mr *MockSkillRegistryMockRecorder) IsActive(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockSkillRegistry)(nil).IsActive), name)
}

// MockSkillConversation is a mock of SkillConversation interface.
type MockSkillConversation struct {
	ctrl     *gomock.Controller
	recorder *MockSkillConversationMockRecorder
	isgomock struct{}
}

// MockSkillConversationMockRecorder is the mock recorder for MockSkillConversation.
type MockSkillConversationMockRecorder struct {
	mock *MockSkillConversation
}

// NewMockSkillConversation creates a new mock instance.
func NewMockSkillConversation(ctrl *gomock.Controller) *MockSkillConversation {
	mock := &MockSkillConversation{ctrl: ctrl}
	mock.recorder = &MockSkillConversationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillConversation) EXPECT() *MockSkillConversationMockRecorder {
	return m.recorder
}

// AddSystemMessage mocks base method.
func (m *MockSkillConversation) AddSystemMessage(content string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSystemMessage", content)
}

// AddSystemMessage indicates an expected call of AddSystemMessage.
func (mr *MockSkillConversationMockRecorder) AddSystemMessage(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSystemMessage", reflect.TypeOf((*MockSkillConversation)(nil).AddSystemMessage), content)
}

// ClearToolFilter mocks base method.
func (m *MockSkillConversation) ClearToolFilter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearToolFilter")
}

// ClearToolFilter indicates an expected call of ClearToolFilter.
func (mr *MockSkillConversationMockRecorder) ClearToolFilter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearToolFilter", reflect.TypeOf((*MockSkillConversation)(nil).ClearToolFilter))
}

// GetMetadata mocks base method.
func (m *MockSkillConversation) GetMetadata(key string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockSkillConversationMockRecorder) GetMetadata(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockSkillConversation)(nil).GetMetadata), key)
}

// SetMetadata mocks base method.
func (m *MockSkillConversation) SetMetadata(key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetadata", key, value)
}

// SetMetadata indicates an expected call of SetMetadata.
func (mr *MockSkillConversationMockRecorder) SetMetadata(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetadata", reflect.TypeOf((*MockSkillConversation)(nil).SetMetadata), key, value)
}

// SetToolFilter mocks base method.
func (m *MockSkillConversation) SetToolFilter(allowedTools []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToolFilter", allowedTools)
}

// SetToolFilter indicates an expected call of SetToolFilter.
func (mr *MockSkillConversationMockRecorder) SetToolFilter(allowedTools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToolFilter", reflect.TypeOf((*MockSkillConversation)(nil).SetToolFilter), allowedTools)
}

// MockPhaseSkill is a mock of PhaseSkill interface.
type MockPhaseSkill struct {
	ctrl     *gomock.Controller
	recorder *MockPhaseSkillMockRecorder
	isgomock struct{}
}

// MockPhaseSkillMockRecorder is the mock recorder for MockPhaseSkill.
type MockPhaseSkillMockRecorder struct {
	mock *MockPhaseSkill
}

// NewMockPhaseSkill creates a new mock instance.
func NewMockPhaseSkill(ctrl *gomock.Controller) *MockPhaseSkill {
	mock := &MockPhaseSkill{ctrl: ctrl}
	mock.recorder = &MockPhaseSkillMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhaseSkill) EXPECT() *MockPhaseSkillMockRecorder {
	return m.recorder
}

// GetAllowedTools mocks base method.
func (m *MockPhaseSkill) GetAllowedTools() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedTools")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedTools indicates an expected call of GetAllowedTools.
func (mr *MockPhaseSkillMockRecorder) GetAllowedTools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedTools", reflect.TypeOf((*MockPhaseSkill)(nil).GetAllowedTools))
}

// GetContent mocks base method.
func (m *MockPhaseSkill) GetContent() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContent indicates an expected call of GetContent.
func (mr *MockPhaseSkillMockRecorder) GetContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockPhaseSkill)(nil).GetContent))
}

// GetDescription mocks base method.
func (m *MockPhaseSkill) GetDescription() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockPhaseSkillMockRecorder) GetDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockPhaseSkill)(nil).GetDescription))
}

// GetName mocks base method.
func (m *MockPhaseSkill) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockPhaseSkillMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockPhaseSkill)(nil).GetName))
}

// GetRequiresTodo mocks base method.
func (m *MockPhaseSkill) GetRequiresTodo() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequiresTodo")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetRequiresTodo indicates an expected call of GetRequiresTodo.
func (mr *MockPhaseSkillMockRecorder) GetRequiresTodo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequiresTodo", reflect.TypeOf((*MockPhaseSkill)(nil).GetRequiresTodo))
}

// GetTodoTemplate mocks base method.
func (m *MockPhaseSkill) GetTodoTemplate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoTemplate")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTodoTemplate indicates an expected call of GetTodoTemplate.
func (mr *MockPhaseSkillMockRecorder) GetTodoTemplate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoTemplate", reflect.TypeOf((*MockPhaseSkill)(nil).GetTodoTemplate))
}
