// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: acp.proto

package acppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_acp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterAgentRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterAgentRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_acp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *RegisterAgentResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_acp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnregisterAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DiscoverAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverAgentsRequest) Reset() {
	*x = DiscoverAgentsRequest{}
	mi := &file_acp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverAgentsRequest) ProtoMessage() {}

func (x *DiscoverAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverAgentsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverAgentsRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverAgentsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiscoverAgentsRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DiscoverAgentsRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DiscoverAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverAgentsResponse) Reset() {
	*x = DiscoverAgentsResponse{}
	mi := &file_acp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverAgentsResponse) ProtoMessage() {}

func (x *DiscoverAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverAgentsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverAgentsResponse) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoRequest) Reset() {
	*x = GetAgentInfoRequest{}
	mi := &file_acp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoRequest) ProtoMessage() {}

func (x *GetAgentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAgentInfoRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentInfoRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CapabilityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capabilities    []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Context         *GrantContext          `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_acp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CapabilityRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CapabilityRequest) GetContext() *GrantContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CapabilityRevocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRevocation) Reset() {
	*x = CapabilityRevocation{}
	mi := &file_acp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRevocation) ProtoMessage() {}

func (x *CapabilityRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRevocation.ProtoReflect.Descriptor instead.
func (*CapabilityRevocation) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityRevocation) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_acp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ContextDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AddedFiles    []string               `protobuf:"bytes,2,rep,name=added_files,json=addedFiles,proto3" json:"added_files,omitempty"`
	RemovedFiles  []string               `protobuf:"bytes,3,rep,name=removed_files,json=removedFiles,proto3" json:"removed_files,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextDelta) Reset() {
	*x = ContextDelta{}
	mi := &file_acp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextDelta) ProtoMessage() {}

func (x *ContextDelta) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextDelta.ProtoReflect.Descriptor instead.
func (*ContextDelta) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{9}
}

func (x *ContextDelta) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContextDelta) GetAddedFiles() []string {
	if x != nil {
		return x.AddedFiles
	}
	return nil
}

func (x *ContextDelta) GetRemovedFiles() []string {
	if x != nil {
		return x.RemovedFiles
	}
	return nil
}

func (x *ContextDelta) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ContextHandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextHandleRequest) Reset() {
	*x = ContextHandleRequest{}
	mi := &file_acp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextHandleRequest) ProtoMessage() {}

func (x *ContextHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextHandleRequest.ProtoReflect.Descriptor instead.
func (*ContextHandleRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{10}
}

func (x *ContextHandleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContextHandleRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContextData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextData) Reset() {
	*x = ContextData{}
	mi := &file_acp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextData) ProtoMessage() {}

func (x *ContextData) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextData.ProtoReflect.Descriptor instead.
func (*ContextData) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{11}
}

func (x *ContextData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContextData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Context       *EditorContext         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamRequest) Reset() {
	*x = TaskStreamRequest{}
	mi := &file_acp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamRequest) ProtoMessage() {}

func (x *TaskStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamRequest.ProtoReflect.Descriptor instead.
func (*TaskStreamRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{12}
}

func (x *TaskStreamRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStreamRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskStreamRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TaskStreamRequest) GetContext() *EditorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type TaskSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	TaskIds       []string               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSubscription) Reset() {
	*x = TaskSubscription{}
	mi := &file_acp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubscription) ProtoMessage() {}

func (x *TaskSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubscription.ProtoReflect.Descriptor instead.
func (*TaskSubscription) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{13}
}

func (x *TaskSubscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *TaskSubscription) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type P2PEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	TargetAgentId string                 `protobuf:"bytes,2,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PEndpointRequest) Reset() {
	*x = P2PEndpointRequest{}
	mi := &file_acp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PEndpointRequest) ProtoMessage() {}

func (x *P2PEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PEndpointRequest.ProtoReflect.Descriptor instead.
func (*P2PEndpointRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{14}
}

func (x *P2PEndpointRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *P2PEndpointRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

type P2PHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PHandshake) Reset() {
	*x = P2PHandshake{}
	mi := &file_acp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PHandshake) ProtoMessage() {}

func (x *P2PHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PHandshake.ProtoReflect.Descriptor instead.
func (*P2PHandshake) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{15}
}

func (x *P2PHandshake) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type P2PConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PConnectionInfo) Reset() {
	*x = P2PConnectionInfo{}
	mi := &file_acp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PConnectionInfo) ProtoMessage() {}

func (x *P2PConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PConnectionInfo.ProtoReflect.Descriptor instead.
func (*P2PConnectionInfo) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{16}
}

func (x *P2PConnectionInfo) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *P2PConnectionInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ToolExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionRequest) Reset() {
	*x = ToolExecutionRequest{}
	mi := &file_acp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionRequest) ProtoMessage() {}

func (x *ToolExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionRequest.ProtoReflect.Descriptor instead.
func (*ToolExecutionRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{17}
}

func (x *ToolExecutionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToolExecutionRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolExecutionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionEvent) Reset() {
	*x = ToolExecutionEvent{}
	mi := &file_acp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionEvent) ProtoMessage() {}

func (x *ToolExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionEvent.ProtoReflect.Descriptor instead.
func (*ToolExecutionEvent) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{18}
}

func (x *ToolExecutionEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ToolExecutionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolExecutionEvent) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolExecutionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ToolApproval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Remember      bool                   `protobuf:"varint,2,opt,name=remember,proto3" json:"remember,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolApproval) Reset() {
	*x = ToolApproval{}
	mi := &file_acp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolApproval) ProtoMessage() {}

func (x *ToolApproval) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolApproval.ProtoReflect.Descriptor instead.
func (*ToolApproval) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{19}
}

func (x *ToolApproval) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ToolApproval) GetRemember() bool {
	if x != nil {
		return x.Remember
	}
	return false
}

type ToolRejection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRejection) Reset() {
	*x = ToolRejection{}
	mi := &file_acp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRejection) ProtoMessage() {}

func (x *ToolRejection) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRejection.ProtoReflect.Descriptor instead.
func (*ToolRejection) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{20}
}

func (x *ToolRejection) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ToolRejection) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_acp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{21}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Context       *EditorContext         `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_acp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{22}
}

func (x *SendMessageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetContext() *EditorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Message               `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_acp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{23}
}

func (x *SendMessageResponse) GetResponse() *Message {
	if x != nil {
		return x.Response
	}
	return nil
}

// Editor context and inline features
type DocumentSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	LanguageId    string                 `protobuf:"bytes,2,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Selection     *Range                 `protobuf:"bytes,4,opt,name=selection,proto3" json:"selection,omitempty"`
	VisibleRanges []*Range               `protobuf:"bytes,5,rep,name=visible_ranges,json=visibleRanges,proto3" json:"visible_ranges,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	WorkspaceRoot string                 `protobuf:"bytes,7,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentSnapshot) Reset() {
	*x = DocumentSnapshot{}
	mi := &file_acp_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSnapshot) ProtoMessage() {}

func (x *DocumentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSnapshot.ProtoReflect.Descriptor instead.
func (*DocumentSnapshot) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{24}
}

func (x *DocumentSnapshot) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DocumentSnapshot) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *DocumentSnapshot) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentSnapshot) GetSelection() *Range {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *DocumentSnapshot) GetVisibleRanges() []*Range {
	if x != nil {
		return x.VisibleRanges
	}
	return nil
}

func (x *DocumentSnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentSnapshot) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *DocumentSnapshot) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EditorContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Document         *DocumentSnapshot      `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	RelatedDocuments []*DocumentSnapshot    `protobuf:"bytes,2,rep,name=related_documents,json=relatedDocuments,proto3" json:"related_documents,omitempty"`
	Symbols          []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditorContext) Reset() {
	*x = EditorContext{}
	mi := &file_acp_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorContext) ProtoMessage() {}

func (x *EditorContext) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorContext.ProtoReflect.Descriptor instead.
func (*EditorContext) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{25}
}

func (x *EditorContext) GetDocument() *DocumentSnapshot {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *EditorContext) GetRelatedDocuments() []*DocumentSnapshot {
	if x != nil {
		return x.RelatedDocuments
	}
	return nil
}

func (x *EditorContext) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *EditorContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InlineCompletionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context        *EditorContext         `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Prompt         string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxSuggestions int32                  `protobuf:"varint,5,opt,name=max_suggestions,json=maxSuggestions,proto3" json:"max_suggestions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InlineCompletionRequest) Reset() {
	*x = InlineCompletionRequest{}
	mi := &file_acp_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineCompletionRequest) ProtoMessage() {}

func (x *InlineCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineCompletionRequest.ProtoReflect.Descriptor instead.
func (*InlineCompletionRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{26}
}

func (x *InlineCompletionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InlineCompletionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InlineCompletionRequest) GetContext() *EditorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InlineCompletionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *InlineCompletionRequest) GetMaxSuggestions() int32 {
	if x != nil {
		return x.MaxSuggestions
	}
	return 0
}

type InlineCompletionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompletionId  string                 `protobuf:"bytes,1,opt,name=completion_id,json=completionId,proto3" json:"completion_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineCompletionEvent) Reset() {
	*x = InlineCompletionEvent{}
	mi := &file_acp_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineCompletionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineCompletionEvent) ProtoMessage() {}

func (x *InlineCompletionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineCompletionEvent.ProtoReflect.Descriptor instead.
func (*InlineCompletionEvent) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{27}
}

func (x *InlineCompletionEvent) GetCompletionId() string {
	if x != nil {
		return x.CompletionId
	}
	return ""
}

func (x *InlineCompletionEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InlineCompletionEvent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *InlineCompletionEvent) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *InlineCompletionEvent) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TextEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Range         *Range                 `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	NewText       string                 `protobuf:"bytes,3,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEdit) Reset() {
	*x = TextEdit{}
	mi := &file_acp_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEdit) ProtoMessage() {}

func (x *TextEdit) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEdit.ProtoReflect.Descriptor instead.
func (*TextEdit) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{28}
}

func (x *TextEdit) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TextEdit) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *TextEdit) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

type ProposedEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Edits         []*TextEdit            `protobuf:"bytes,2,rep,name=edits,proto3" json:"edits,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposedEdit) Reset() {
	*x = ProposedEdit{}
	mi := &file_acp_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposedEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposedEdit) ProtoMessage() {}

func (x *ProposedEdit) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposedEdit.ProtoReflect.Descriptor instead.
func (*ProposedEdit) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{29}
}

func (x *ProposedEdit) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ProposedEdit) GetEdits() []*TextEdit {
	if x != nil {
		return x.Edits
	}
	return nil
}

func (x *ProposedEdit) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProposedEdit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposedEdit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProposedEdit) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type ProposeEditsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Instruction    string                 `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Context        *EditorContext         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Apply          bool                   `protobuf:"varint,5,opt,name=apply,proto3" json:"apply,omitempty"`
	MaxSuggestions int32                  `protobuf:"varint,6,opt,name=max_suggestions,json=maxSuggestions,proto3" json:"max_suggestions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProposeEditsRequest) Reset() {
	*x = ProposeEditsRequest{}
	mi := &file_acp_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeEditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeEditsRequest) ProtoMessage() {}

func (x *ProposeEditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeEditsRequest.ProtoReflect.Descriptor instead.
func (*ProposeEditsRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{30}
}

func (x *ProposeEditsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProposeEditsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProposeEditsRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *ProposeEditsRequest) GetContext() *EditorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ProposeEditsRequest) GetApply() bool {
	if x != nil {
		return x.Apply
	}
	return false
}

func (x *ProposeEditsRequest) GetMaxSuggestions() int32 {
	if x != nil {
		return x.MaxSuggestions
	}
	return 0
}

type ProposeEditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Edits         []*ProposedEdit        `protobuf:"bytes,3,rep,name=edits,proto3" json:"edits,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeEditsResponse) Reset() {
	*x = ProposeEditsResponse{}
	mi := &file_acp_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeEditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeEditsResponse) ProtoMessage() {}

func (x *ProposeEditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeEditsResponse.ProtoReflect.Descriptor instead.
func (*ProposeEditsResponse) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{31}
}

func (x *ProposeEditsResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ProposeEditsResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProposeEditsResponse) GetEdits() []*ProposedEdit {
	if x != nil {
		return x.Edits
	}
	return nil
}

func (x *ProposeEditsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ApplyEditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Edits         []*TextEdit            `protobuf:"bytes,3,rep,name=edits,proto3" json:"edits,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	DryRun        bool                   `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyEditsRequest) Reset() {
	*x = ApplyEditsRequest{}
	mi := &file_acp_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyEditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyEditsRequest) ProtoMessage() {}

func (x *ApplyEditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyEditsRequest.ProtoReflect.Descriptor instead.
func (*ApplyEditsRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{32}
}

func (x *ApplyEditsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ApplyEditsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApplyEditsRequest) GetEdits() []*TextEdit {
	if x != nil {
		return x.Edits
	}
	return nil
}

func (x *ApplyEditsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ApplyEditsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ApplyEditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Files         []string               `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyEditsResponse) Reset() {
	*x = ApplyEditsResponse{}
	mi := &file_acp_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyEditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyEditsResponse) ProtoMessage() {}

func (x *ApplyEditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyEditsResponse.ProtoReflect.Descriptor instead.
func (*ApplyEditsResponse) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{33}
}

func (x *ApplyEditsResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyEditsResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ApplyEditsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateEditorStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context         *EditorContext         `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Diagnostics     []string               `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RequestTodoSync bool                   `protobuf:"varint,5,opt,name=request_todo_sync,json=requestTodoSync,proto3" json:"request_todo_sync,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateEditorStateRequest) Reset() {
	*x = UpdateEditorStateRequest{}
	mi := &file_acp_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEditorStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEditorStateRequest) ProtoMessage() {}

func (x *UpdateEditorStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEditorStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateEditorStateRequest) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateEditorStateRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateEditorStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateEditorStateRequest) GetContext() *EditorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateEditorStateRequest) GetDiagnostics() []string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *UpdateEditorStateRequest) GetRequestTodoSync() bool {
	if x != nil {
		return x.RequestTodoSync
	}
	return false
}

type UpdateEditorStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlanState       string                 `protobuf:"bytes,1,opt,name=plan_state,json=planState,proto3" json:"plan_state,omitempty"`
	TodoState       string                 `protobuf:"bytes,2,opt,name=todo_state,json=todoState,proto3" json:"todo_state,omitempty"`
	Approvals       []string               `protobuf:"bytes,3,rep,name=approvals,proto3" json:"approvals,omitempty"`
	ToolsInProgress []string               `protobuf:"bytes,4,rep,name=tools_in_progress,json=toolsInProgress,proto3" json:"tools_in_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateEditorStateResponse) Reset() {
	*x = UpdateEditorStateResponse{}
	mi := &file_acp_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEditorStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEditorStateResponse) ProtoMessage() {}

func (x *UpdateEditorStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEditorStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateEditorStateResponse) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateEditorStateResponse) GetPlanState() string {
	if x != nil {
		return x.PlanState
	}
	return ""
}

func (x *UpdateEditorStateResponse) GetTodoState() string {
	if x != nil {
		return x.TodoState
	}
	return ""
}

func (x *UpdateEditorStateResponse) GetApprovals() []string {
	if x != nil {
		return x.Approvals
	}
	return nil
}

func (x *UpdateEditorStateResponse) GetToolsInProgress() []string {
	if x != nil {
		return x.ToolsInProgress
	}
	return nil
}

var File_acp_proto protoreflect.FileDescriptor

const file_acp_proto_rawDesc = "" +
	"\n" +
	"\tacp.proto\x12\x0ebuckley.acp.v1\x1a\vtypes.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12N\n" +
	"\bmetadata\x18\x05 \x03(\v22.buckley.acp.v1.RegisterAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x15RegisterAgentResponse\x12/\n" +
	"\x05agent\x18\x01 \x01(\v2\x19.buckley.acp.v1.AgentInfoR\x05agent\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"K\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xcd\x01\n" +
	"\x15DiscoverAgentsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12C\n" +
	"\x04tags\x18\x03 \x03(\v2/.buckley.acp.v1.DiscoverAgentsRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x16DiscoverAgentsResponse\x121\n" +
	"\x06agents\x18\x01 \x03(\v2\x19.buckley.acp.v1.AgentInfoR\x06agents\"0\n" +
	"\x13GetAgentInfoRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x9a\x01\n" +
	"\x11CapabilityRequest\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x03R\x0fdurationSeconds\x126\n" +
	"\acontext\x18\x03 \x01(\v2\x1c.buckley.acp.v1.GrantContextR\acontext\"1\n" +
	"\x14CapabilityRevocation\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\"\xbe\x01\n" +
	"\x14CreateSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12N\n" +
	"\bmetadata\x18\x02 \x03(\v22.buckley.acp.v1.CreateSessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\fContextDelta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vadded_files\x18\x02 \x03(\tR\n" +
	"addedFiles\x12#\n" +
	"\rremoved_files\x18\x03 \x03(\tR\fremovedFiles\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.buckley.acp.v1.ContextDelta.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x14ContextHandleRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"5\n" +
	"\vContextData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x96\x01\n" +
	"\x11TaskStreamRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x127\n" +
	"\acontext\x18\x04 \x01(\v2\x1d.buckley.acp.v1.EditorContextR\acontext\"F\n" +
	"\x10TaskSubscription\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\tR\ataskIds\"_\n" +
	"\x12P2PEndpointRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12&\n" +
	"\x0ftarget_agent_id\x18\x02 \x01(\tR\rtargetAgentId\"$\n" +
	"\fP2PHandshake\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\\\n" +
	"\x11P2PConnectionInfo\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\xda\x01\n" +
	"\x14ToolExecutionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12T\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v24.buckley.acp.v1.ToolExecutionRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x12ToolExecutionEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"M\n" +
	"\fToolApproval\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1a\n" +
	"\bremember\x18\x02 \x01(\bR\bremember\"J\n" +
	"\rToolRejection\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x9b\x01\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x121\n" +
	"\amessage\x18\x02 \x01(\v2\x17.buckley.acp.v1.MessageR\amessage\x127\n" +
	"\acontext\x18\x03 \x01(\v2\x1d.buckley.acp.v1.EditorContextR\acontext\"J\n" +
	"\x13SendMessageResponse\x123\n" +
	"\bresponse\x18\x01 \x01(\v2\x17.buckley.acp.v1.MessageR\bresponse\"\x9c\x03\n" +
	"\x10DocumentSnapshot\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1f\n" +
	"\vlanguage_id\x18\x02 \x01(\tR\n" +
	"languageId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x123\n" +
	"\tselection\x18\x04 \x01(\v2\x15.buckley.acp.v1.RangeR\tselection\x12<\n" +
	"\x0evisible_ranges\x18\x05 \x03(\v2\x15.buckley.acp.v1.RangeR\rvisibleRanges\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12%\n" +
	"\x0eworkspace_root\x18\a \x01(\tR\rworkspaceRoot\x12J\n" +
	"\bmetadata\x18\b \x03(\v2..buckley.acp.v1.DocumentSnapshot.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\rEditorContext\x12<\n" +
	"\bdocument\x18\x01 \x01(\v2 .buckley.acp.v1.DocumentSnapshotR\bdocument\x12M\n" +
	"\x11related_documents\x18\x02 \x03(\v2 .buckley.acp.v1.DocumentSnapshotR\x10relatedDocuments\x12\x18\n" +
	"\asymbols\x18\x03 \x03(\tR\asymbols\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.buckley.acp.v1.EditorContext.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x17InlineCompletionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x127\n" +
	"\acontext\x18\x03 \x01(\v2\x1d.buckley.acp.v1.EditorContextR\acontext\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12'\n" +
	"\x0fmax_suggestions\x18\x05 \x01(\x05R\x0emaxSuggestions\"\xa6\x01\n" +
	"\x15InlineCompletionEvent\x12#\n" +
	"\rcompletion_id\x18\x01 \x01(\tR\fcompletionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"d\n" +
	"\bTextEdit\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12+\n" +
	"\x05range\x18\x02 \x01(\v2\x15.buckley.acp.v1.RangeR\x05range\x12\x19\n" +
	"\bnew_text\x18\x03 \x01(\tR\anewText\"\xaa\x01\n" +
	"\fProposedEdit\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12.\n" +
	"\x05edits\x18\x02 \x03(\v2\x18.buckley.acp.v1.TextEditR\x05edits\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\"\xe9\x01\n" +
	"\x13ProposeEditsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12 \n" +
	"\vinstruction\x18\x03 \x01(\tR\vinstruction\x127\n" +
	"\acontext\x18\x04 \x01(\v2\x1d.buckley.acp.v1.EditorContextR\acontext\x12\x14\n" +
	"\x05apply\x18\x05 \x01(\bR\x05apply\x12'\n" +
	"\x0fmax_suggestions\x18\x06 \x01(\x05R\x0emaxSuggestions\"\x96\x01\n" +
	"\x14ProposeEditsResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x122\n" +
	"\x05edits\x18\x03 \x03(\v2\x1c.buckley.acp.v1.ProposedEditR\x05edits\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"\xac\x01\n" +
	"\x11ApplyEditsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12.\n" +
	"\x05edits\x18\x03 \x03(\v2\x18.buckley.acp.v1.TextEditR\x05edits\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x17\n" +
	"\adry_run\x18\x05 \x01(\bR\x06dryRun\"^\n" +
	"\x12ApplyEditsResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xdb\x01\n" +
	"\x18UpdateEditorStateRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x127\n" +
	"\acontext\x18\x03 \x01(\v2\x1d.buckley.acp.v1.EditorContextR\acontext\x12 \n" +
	"\vdiagnostics\x18\x04 \x03(\tR\vdiagnostics\x12*\n" +
	"\x11request_todo_sync\x18\x05 \x01(\bR\x0frequestTodoSync\"\xa3\x01\n" +
	"\x19UpdateEditorStateResponse\x12\x1d\n" +
	"\n" +
	"plan_state\x18\x01 \x01(\tR\tplanState\x12\x1d\n" +
	"\n" +
	"todo_state\x18\x02 \x01(\tR\ttodoState\x12\x1c\n" +
	"\tapprovals\x18\x03 \x03(\tR\tapprovals\x12*\n" +
	"\x11tools_in_progress\x18\x04 \x03(\tR\x0ftoolsInProgress2\xf9\x0f\n" +
	"\x12AgentCommunication\x12\\\n" +
	"\rRegisterAgent\x12$.buckley.acp.v1.RegisterAgentRequest\x1a%.buckley.acp.v1.RegisterAgentResponse\x12Q\n" +
	"\x0fUnregisterAgent\x12&.buckley.acp.v1.UnregisterAgentRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\x0eDiscoverAgents\x12%.buckley.acp.v1.DiscoverAgentsRequest\x1a&.buckley.acp.v1.DiscoverAgentsResponse\x12N\n" +
	"\fGetAgentInfo\x12#.buckley.acp.v1.GetAgentInfoRequest\x1a\x19.buckley.acp.v1.AgentInfo\x12S\n" +
	"\x15GetServerCapabilities\x12\x16.google.protobuf.Empty\x1a\".buckley.acp.v1.ServerCapabilities\x12Y\n" +
	"\x13RequestCapabilities\x12!.buckley.acp.v1.CapabilityRequest\x1a\x1f.buckley.acp.v1.CapabilityGrant\x12R\n" +
	"\x12RevokeCapabilities\x12$.buckley.acp.v1.CapabilityRevocation\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rCreateSession\x12$.buckley.acp.v1.CreateSessionRequest\x1a\x17.buckley.acp.v1.Session\x12L\n" +
	"\x14UpdateSessionContext\x12\x1c.buckley.acp.v1.ContextDelta\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x13CreateContextHandle\x12$.buckley.acp.v1.ContextHandleRequest\x1a\x1d.buckley.acp.v1.ContextHandle\x12R\n" +
	"\x14ResolveContextHandle\x12\x1d.buckley.acp.v1.ContextHandle\x1a\x1b.buckley.acp.v1.ContextData\x12L\n" +
	"\n" +
	"StreamTask\x12!.buckley.acp.v1.TaskStreamRequest\x1a\x19.buckley.acp.v1.TaskEvent0\x01\x12T\n" +
	"\x13SubscribeTaskEvents\x12 .buckley.acp.v1.TaskSubscription\x1a\x19.buckley.acp.v1.TaskEvent0\x01\x12Q\n" +
	"\x0eGetP2PEndpoint\x12\".buckley.acp.v1.P2PEndpointRequest\x1a\x1b.buckley.acp.v1.P2PEndpoint\x12Y\n" +
	"\x16EstablishP2PConnection\x12\x1c.buckley.acp.v1.P2PHandshake\x1a!.buckley.acp.v1.P2PConnectionInfo\x12b\n" +
	"\x14RequestToolExecution\x12$.buckley.acp.v1.ToolExecutionRequest\x1a\".buckley.acp.v1.ToolExecutionEvent0\x01\x12L\n" +
	"\x14ApproveToolExecution\x12\x1c.buckley.acp.v1.ToolApproval\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x13RejectToolExecution\x12\x1d.buckley.acp.v1.ToolRejection\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\vSendMessage\x12\".buckley.acp.v1.SendMessageRequest\x1a#.buckley.acp.v1.SendMessageResponse\x12k\n" +
	"\x17StreamInlineCompletions\x12'.buckley.acp.v1.InlineCompletionRequest\x1a%.buckley.acp.v1.InlineCompletionEvent0\x01\x12Y\n" +
	"\fProposeEdits\x12#.buckley.acp.v1.ProposeEditsRequest\x1a$.buckley.acp.v1.ProposeEditsResponse\x12S\n" +
	"\n" +
	"ApplyEdits\x12!.buckley.acp.v1.ApplyEditsRequest\x1a\".buckley.acp.v1.ApplyEditsResponse\x12h\n" +
	"\x11UpdateEditorState\x12(.buckley.acp.v1.UpdateEditorStateRequest\x1a).buckley.acp.v1.UpdateEditorStateResponseB.Z,github.com/odvcencio/buckley/pkg/acp/proto;acppbb\x06proto3"

var (
	file_acp_proto_rawDescOnce sync.Once
	file_acp_proto_rawDescData []byte
)

func file_acp_proto_rawDescGZIP() []byte {
	file_acp_proto_rawDescOnce.Do(func() {
		file_acp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acp_proto_rawDesc), len(file_acp_proto_rawDesc)))
	})
	return file_acp_proto_rawDescData
}

var file_acp_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_acp_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),      // 0: buckley.acp.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),     // 1: buckley.acp.v1.RegisterAgentResponse
	(*UnregisterAgentRequest)(nil),    // 2: buckley.acp.v1.UnregisterAgentRequest
	(*DiscoverAgentsRequest)(nil),     // 3: buckley.acp.v1.DiscoverAgentsRequest
	(*DiscoverAgentsResponse)(nil),    // 4: buckley.acp.v1.DiscoverAgentsResponse
	(*GetAgentInfoRequest)(nil),       // 5: buckley.acp.v1.GetAgentInfoRequest
	(*CapabilityRequest)(nil),         // 6: buckley.acp.v1.CapabilityRequest
	(*CapabilityRevocation)(nil),      // 7: buckley.acp.v1.CapabilityRevocation
	(*CreateSessionRequest)(nil),      // 8: buckley.acp.v1.CreateSessionRequest
	(*ContextDelta)(nil),              // 9: buckley.acp.v1.ContextDelta
	(*ContextHandleRequest)(nil),      // 10: buckley.acp.v1.ContextHandleRequest
	(*ContextData)(nil),               // 11: buckley.acp.v1.ContextData
	(*TaskStreamRequest)(nil),         // 12: buckley.acp.v1.TaskStreamRequest
	(*TaskSubscription)(nil),          // 13: buckley.acp.v1.TaskSubscription
	(*P2PEndpointRequest)(nil),        // 14: buckley.acp.v1.P2PEndpointRequest
	(*P2PHandshake)(nil),              // 15: buckley.acp.v1.P2PHandshake
	(*P2PConnectionInfo)(nil),         // 16: buckley.acp.v1.P2PConnectionInfo
	(*ToolExecutionRequest)(nil),      // 17: buckley.acp.v1.ToolExecutionRequest
	(*ToolExecutionEvent)(nil),        // 18: buckley.acp.v1.ToolExecutionEvent
	(*ToolApproval)(nil),              // 19: buckley.acp.v1.ToolApproval
	(*ToolRejection)(nil),             // 20: buckley.acp.v1.ToolRejection
	(*Message)(nil),                   // 21: buckley.acp.v1.Message
	(*SendMessageRequest)(nil),        // 22: buckley.acp.v1.SendMessageRequest
	(*SendMessageResponse)(nil),       // 23: buckley.acp.v1.SendMessageResponse
	(*DocumentSnapshot)(nil),          // 24: buckley.acp.v1.DocumentSnapshot
	(*EditorContext)(nil),             // 25: buckley.acp.v1.EditorContext
	(*InlineCompletionRequest)(nil),   // 26: buckley.acp.v1.InlineCompletionRequest
	(*InlineCompletionEvent)(nil),     // 27: buckley.acp.v1.InlineCompletionEvent
	(*TextEdit)(nil),                  // 28: buckley.acp.v1.TextEdit
	(*ProposedEdit)(nil),              // 29: buckley.acp.v1.ProposedEdit
	(*ProposeEditsRequest)(nil),       // 30: buckley.acp.v1.ProposeEditsRequest
	(*ProposeEditsResponse)(nil),      // 31: buckley.acp.v1.ProposeEditsResponse
	(*ApplyEditsRequest)(nil),         // 32: buckley.acp.v1.ApplyEditsRequest
	(*ApplyEditsResponse)(nil),        // 33: buckley.acp.v1.ApplyEditsResponse
	(*UpdateEditorStateRequest)(nil),  // 34: buckley.acp.v1.UpdateEditorStateRequest
	(*UpdateEditorStateResponse)(nil), // 35: buckley.acp.v1.UpdateEditorStateResponse
	nil,                               // 36: buckley.acp.v1.RegisterAgentRequest.MetadataEntry
	nil,                               // 37: buckley.acp.v1.DiscoverAgentsRequest.TagsEntry
	nil,                               // 38: buckley.acp.v1.CreateSessionRequest.MetadataEntry
	nil,                               // 39: buckley.acp.v1.ContextDelta.MetadataEntry
	nil,                               // 40: buckley.acp.v1.ToolExecutionRequest.ParametersEntry
	nil,                               // 41: buckley.acp.v1.DocumentSnapshot.MetadataEntry
	nil,                               // 42: buckley.acp.v1.EditorContext.MetadataEntry
	(*AgentInfo)(nil),                 // 43: buckley.acp.v1.AgentInfo
	(*GrantContext)(nil),              // 44: buckley.acp.v1.GrantContext
	(*timestamppb.Timestamp)(nil),     // 45: google.protobuf.Timestamp
	(*Range)(nil),                     // 46: buckley.acp.v1.Range
	(*emptypb.Empty)(nil),             // 47: google.protobuf.Empty
	(*ContextHandle)(nil),             // 48: buckley.acp.v1.ContextHandle
	(*ServerCapabilities)(nil),        // 49: buckley.acp.v1.ServerCapabilities
	(*CapabilityGrant)(nil),           // 50: buckley.acp.v1.CapabilityGrant
	(*Session)(nil),                   // 51: buckley.acp.v1.Session
	(*TaskEvent)(nil),                 // 52: buckley.acp.v1.TaskEvent
	(*P2PEndpoint)(nil),               // 53: buckley.acp.v1.P2PEndpoint
}
var file_acp_proto_depIdxs = []int32{
	36, // 0: buckley.acp.v1.RegisterAgentRequest.metadata:type_name -> buckley.acp.v1.RegisterAgentRequest.MetadataEntry
	43, // 1: buckley.acp.v1.RegisterAgentResponse.agent:type_name -> buckley.acp.v1.AgentInfo
	37, // 2: buckley.acp.v1.DiscoverAgentsRequest.tags:type_name -> buckley.acp.v1.DiscoverAgentsRequest.TagsEntry
	43, // 3: buckley.acp.v1.DiscoverAgentsResponse.agents:type_name -> buckley.acp.v1.AgentInfo
	44, // 4: buckley.acp.v1.CapabilityRequest.context:type_name -> buckley.acp.v1.GrantContext
	38, // 5: buckley.acp.v1.CreateSessionRequest.metadata:type_name -> buckley.acp.v1.CreateSessionRequest.MetadataEntry
	39, // 6: buckley.acp.v1.ContextDelta.metadata:type_name -> buckley.acp.v1.ContextDelta.MetadataEntry
	25, // 7: buckley.acp.v1.TaskStreamRequest.context:type_name -> buckley.acp.v1.EditorContext
	40, // 8: buckley.acp.v1.ToolExecutionRequest.parameters:type_name -> buckley.acp.v1.ToolExecutionRequest.ParametersEntry
	45, // 9: buckley.acp.v1.ToolExecutionEvent.timestamp:type_name -> google.protobuf.Timestamp
	21, // 10: buckley.acp.v1.SendMessageRequest.message:type_name -> buckley.acp.v1.Message
	25, // 11: buckley.acp.v1.SendMessageRequest.context:type_name -> buckley.acp.v1.EditorContext
	21, // 12: buckley.acp.v1.SendMessageResponse.response:type_name -> buckley.acp.v1.Message
	46, // 13: buckley.acp.v1.DocumentSnapshot.selection:type_name -> buckley.acp.v1.Range
	46, // 14: buckley.acp.v1.DocumentSnapshot.visible_ranges:type_name -> buckley.acp.v1.Range
	41, // 15: buckley.acp.v1.DocumentSnapshot.metadata:type_name -> buckley.acp.v1.DocumentSnapshot.MetadataEntry
	24, // 16: buckley.acp.v1.EditorContext.document:type_name -> buckley.acp.v1.DocumentSnapshot
	24, // 17: buckley.acp.v1.EditorContext.related_documents:type_name -> buckley.acp.v1.DocumentSnapshot
	42, // 18: buckley.acp.v1.EditorContext.metadata:type_name -> buckley.acp.v1.EditorContext.MetadataEntry
	25, // 19: buckley.acp.v1.InlineCompletionRequest.context:type_name -> buckley.acp.v1.EditorContext
	46, // 20: buckley.acp.v1.TextEdit.range:type_name -> buckley.acp.v1.Range
	28, // 21: buckley.acp.v1.ProposedEdit.edits:type_name -> buckley.acp.v1.TextEdit
	25, // 22: buckley.acp.v1.ProposeEditsRequest.context:type_name -> buckley.acp.v1.EditorContext
	29, // 23: buckley.acp.v1.ProposeEditsResponse.edits:type_name -> buckley.acp.v1.ProposedEdit
	28, // 24: buckley.acp.v1.ApplyEditsRequest.edits:type_name -> buckley.acp.v1.TextEdit
	25, // 25: buckley.acp.v1.UpdateEditorStateRequest.context:type_name -> buckley.acp.v1.EditorContext
	0,  // 26: buckley.acp.v1.AgentCommunication.RegisterAgent:input_type -> buckley.acp.v1.RegisterAgentRequest
	2,  // 27: buckley.acp.v1.AgentCommunication.UnregisterAgent:input_type -> buckley.acp.v1.UnregisterAgentRequest
	3,  // 28: buckley.acp.v1.AgentCommunication.DiscoverAgents:input_type -> buckley.acp.v1.DiscoverAgentsRequest
	5,  // 29: buckley.acp.v1.AgentCommunication.GetAgentInfo:input_type -> buckley.acp.v1.GetAgentInfoRequest
	47, // 30: buckley.acp.v1.AgentCommunication.GetServerCapabilities:input_type -> google.protobuf.Empty
	6,  // 31: buckley.acp.v1.AgentCommunication.RequestCapabilities:input_type -> buckley.acp.v1.CapabilityRequest
	7,  // 32: buckley.acp.v1.AgentCommunication.RevokeCapabilities:input_type -> buckley.acp.v1.CapabilityRevocation
	8,  // 33: buckley.acp.v1.AgentCommunication.CreateSession:input_type -> buckley.acp.v1.CreateSessionRequest
	9,  // 34: buckley.acp.v1.AgentCommunication.UpdateSessionContext:input_type -> buckley.acp.v1.ContextDelta
	10, // 35: buckley.acp.v1.AgentCommunication.CreateContextHandle:input_type -> buckley.acp.v1.ContextHandleRequest
	48, // 36: buckley.acp.v1.AgentCommunication.ResolveContextHandle:input_type -> buckley.acp.v1.ContextHandle
	12, // 37: buckley.acp.v1.AgentCommunication.StreamTask:input_type -> buckley.acp.v1.TaskStreamRequest
	13, // 38: buckley.acp.v1.AgentCommunication.SubscribeTaskEvents:input_type -> buckley.acp.v1.TaskSubscription
	14, // 39: buckley.acp.v1.AgentCommunication.GetP2PEndpoint:input_type -> buckley.acp.v1.P2PEndpointRequest
	15, // 40: buckley.acp.v1.AgentCommunication.EstablishP2PConnection:input_type -> buckley.acp.v1.P2PHandshake
	17, // 41: buckley.acp.v1.AgentCommunication.RequestToolExecution:input_type -> buckley.acp.v1.ToolExecutionRequest
	19, // 42: buckley.acp.v1.AgentCommunication.ApproveToolExecution:input_type -> buckley.acp.v1.ToolApproval
	20, // 43: buckley.acp.v1.AgentCommunication.RejectToolExecution:input_type -> buckley.acp.v1.ToolRejection
	22, // 44: buckley.acp.v1.AgentCommunication.SendMessage:input_type -> buckley.acp.v1.SendMessageRequest
	26, // 45: buckley.acp.v1.AgentCommunication.StreamInlineCompletions:input_type -> buckley.acp.v1.InlineCompletionRequest
	30, // 46: buckley.acp.v1.AgentCommunication.ProposeEdits:input_type -> buckley.acp.v1.ProposeEditsRequest
	32, // 47: buckley.acp.v1.AgentCommunication.ApplyEdits:input_type -> buckley.acp.v1.ApplyEditsRequest
	34, // 48: buckley.acp.v1.AgentCommunication.UpdateEditorState:input_type -> buckley.acp.v1.UpdateEditorStateRequest
	1,  // 49: buckley.acp.v1.AgentCommunication.RegisterAgent:output_type -> buckley.acp.v1.RegisterAgentResponse
	47, // 50: buckley.acp.v1.AgentCommunication.UnregisterAgent:output_type -> google.protobuf.Empty
	4,  // 51: buckley.acp.v1.AgentCommunication.DiscoverAgents:output_type -> buckley.acp.v1.DiscoverAgentsResponse
	43, // 52: buckley.acp.v1.AgentCommunication.GetAgentInfo:output_type -> buckley.acp.v1.AgentInfo
	49, // 53: buckley.acp.v1.AgentCommunication.GetServerCapabilities:output_type -> buckley.acp.v1.ServerCapabilities
	50, // 54: buckley.acp.v1.AgentCommunication.RequestCapabilities:output_type -> buckley.acp.v1.CapabilityGrant
	47, // 55: buckley.acp.v1.AgentCommunication.RevokeCapabilities:output_type -> google.protobuf.Empty
	51, // 56: buckley.acp.v1.AgentCommunication.CreateSession:output_type -> buckley.acp.v1.Session
	47, // 57: buckley.acp.v1.AgentCommunication.UpdateSessionContext:output_type -> google.protobuf.Empty
	48, // 58: buckley.acp.v1.AgentCommunication.CreateContextHandle:output_type -> buckley.acp.v1.ContextHandle
	11, // 59: buckley.acp.v1.AgentCommunication.ResolveContextHandle:output_type -> buckley.acp.v1.ContextData
	52, // 60: buckley.acp.v1.AgentCommunication.StreamTask:output_type -> buckley.acp.v1.TaskEvent
	52, // 61: buckley.acp.v1.AgentCommunication.SubscribeTaskEvents:output_type -> buckley.acp.v1.TaskEvent
	53, // 62: buckley.acp.v1.AgentCommunication.GetP2PEndpoint:output_type -> buckley.acp.v1.P2PEndpoint
	16, // 63: buckley.acp.v1.AgentCommunication.EstablishP2PConnection:output_type -> buckley.acp.v1.P2PConnectionInfo
	18, // 64: buckley.acp.v1.AgentCommunication.RequestToolExecution:output_type -> buckley.acp.v1.ToolExecutionEvent
	47, // 65: buckley.acp.v1.AgentCommunication.ApproveToolExecution:output_type -> google.protobuf.Empty
	47, // 66: buckley.acp.v1.AgentCommunication.RejectToolExecution:output_type -> google.protobuf.Empty
	23, // 67: buckley.acp.v1.AgentCommunication.SendMessage:output_type -> buckley.acp.v1.SendMessageResponse
	27, // 68: buckley.acp.v1.AgentCommunication.StreamInlineCompletions:output_type -> buckley.acp.v1.InlineCompletionEvent
	31, // 69: buckley.acp.v1.AgentCommunication.ProposeEdits:output_type -> buckley.acp.v1.ProposeEditsResponse
	33, // 70: buckley.acp.v1.AgentCommunication.ApplyEdits:output_type -> buckley.acp.v1.ApplyEditsResponse
	35, // 71: buckley.acp.v1.AgentCommunication.UpdateEditorState:output_type -> buckley.acp.v1.UpdateEditorStateResponse
	49, // [49:72] is the sub-list for method output_type
	26, // [26:49] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_acp_proto_init() }
func file_acp_proto_init() {
	if File_acp_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acp_proto_rawDesc), len(file_acp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acp_proto_goTypes,
		DependencyIndexes: file_acp_proto_depIdxs,
		MessageInfos:      file_acp_proto_msgTypes,
	}.Build()
	File_acp_proto = out.File
	file_acp_proto_goTypes = nil
	file_acp_proto_depIdxs = nil
}
