// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odvcencio/buckley/pkg/prompts (interfaces: PersonaProvider)
//
// Generated by this command:
//
//	mockgen -package=prompts -destination=mock_persona_provider_test.go github.com/odvcencio/buckley/pkg/prompts PersonaProvider
//

// Package prompts is a generated GoMock package.
package prompts

import (
	reflect "reflect"

	personality "github.com/odvcencio/buckley/pkg/personality"
	gomock "go.uber.org/mock/gomock"
)

// MockPersonaProvider is a mock of PersonaProvider interface.
type MockPersonaProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPersonaProviderMockRecorder
	isgomock struct{}
}

// MockPersonaProviderMockRecorder is the mock recorder for MockPersonaProvider.
type MockPersonaProviderMockRecorder struct {
	mock *MockPersonaProvider
}

// NewMockPersonaProvider creates a new mock instance.
func NewMockPersonaProvider(ctrl *gomock.Controller) *MockPersonaProvider {
	mock := &MockPersonaProvider{ctrl: ctrl}
	mock.recorder = &MockPersonaProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonaProvider) EXPECT() *MockPersonaProviderMockRecorder {
	return m.recorder
}

// PersonaForPhase mocks base method.
func (m *MockPersonaProvider) PersonaForPhase(phase string) *personality.PersonaProfile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersonaForPhase", phase)
	ret0, _ := ret[0].(*personality.PersonaProfile)
	return ret0
}

// PersonaForPhase indicates an expected call of PersonaForPhase.
func (mr *MockPersonaProviderMockRecorder) PersonaForPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersonaForPhase", reflect.TypeOf((*MockPersonaProvider)(nil).PersonaForPhase), phase)
}
